### ISSUE TITLE
Continuous Finger Control using API

### ISSUE THREAD

**Issue by deepakgopinath** [Kinovarobotics/kinova-ros#107]
Hi, 

We have a JACO 7-dof (j2s7s300) arm using the Kinova API and ROS. We tested the finger action client to command the fingers to a specified position and it works well. 

However, we are interested in controlling the fingers via an external joystick which requires continuous transmission of commands to the fingers from the joystick. We used the function **kinova_comm_.setFingerPositions()** to achieve the behavior, however, the finger motion is slow and very jerky when controlled by the joystick (continuous commands). 

The kinova joystick is able to the fingers very smoothly and in a continuous manner. We want to achieve similar performance using our external joystick and the API. However there are no other API functions besides **kinova_comm_.setFingerPositions()** that are available for use. And this particular function seems to be designed for a single command which sets the finger position once and for all and therefore is not suitable for continuous operation. 

What would be possible approaches/workarounds to make the finger motion smoother using the API when commands are sent continuously using an external joystick. Any thoughts/suggestions would be highly appreciated.

Thank you very much
Sincerely
Deepak.

**Comment by martine1406** [comment]
Hi Deepak

the best way would be to send velocity commands. you can modify cartesianVelocityCallback in kinova_driver/src/kinova_arm.cpp and setCartesianVelocities in kinova_driver/src/kinova_comm.cpp
to include velocity commands to the fingers as well. 
The TrajectoryPoint structure and the sendAdvanceTrajectory API functions are configured to accept commands sent to the fingers as well (see Kinova API html documentation by downloading the Kinova SDK from the Kinova website for more details).
Another alternative would be to change 
kinova_angular.Position.Type = ANGULAR_POSITION
to
kinova_angular.Position.Type = ANGULAR_VELOCITY
in function kinova_comm_.setFingerPositions()

Negative values sent to the fingers in the velocity point will tend to open them and positive values will tend to close them 

Let me know if this is clear enough. 
Thanks

Martine
