### ISSUE TITLE
MoveIt compatible FollowJointTrajectory action interface

### ISSUE THREAD

**Issue by fivef** [Kinovarobotics/kinova-ros#12]
I am missing the FollowJointTrajectory action interface to communicate with MoveIt!.
Has someone created an adapter for that or is there a MoveIt! interface to communicate with this package I am not aware of?

**Comment by davetcoleman** [comment]
I've been looking through wpi_jaco_wrapper, it looks really promising. Any progress on getting an official controller in this ``jaco-ros`` repo?

**Comment by davetcoleman** [comment]
@peci1 I'd like to try your new feature, and help with getting it merged in. Any progress on it?

@jpmerc I've been working on using the ``wpi_jaco_wrapper`` all morning but it seems to be fairly behind on Jaco's API and firmware. It's not publishing the correct joint angles, for one.

**Comment by peci1** [comment]
@davetcoleman Have a look at https://github.com/peci1/jaco-ros/tree/moveit-integration-sensors . There's been some more work merged in, but FollowJointTrajectory has still been working and we've updated it for the new API recently, so that it can merge into your master. Tell me if you'd be interested in merging all our changes ( https://github.com/Kinovarobotics/jaco-ros/compare/master...peci1:moveit-integration-sensors ), or just separating the FollowJointTrajectory part.

**Comment by davetcoleman** [comment]
@peci1 the moveit-integration-sensors branch is great, I got it working (see https://github.com/peci1/jaco-ros/pull/1), thanks!

**Comment by davetcoleman** [comment]
@francoisferland are you interested in having the trajectory controller and moveit packages merged in at some point?

**Comment by francoisferland** [comment]
Actually, that's being worked on at the moment, but it relies on a newer, lower-level API we hope to release soon. FollowJointTrajectory will eventually be provided by ros_control's implementation.

**Comment by lorenzoriano** [comment]
Any update on the current status of MoveIt compatibility?

**Comment by JenniferBuehler** [comment]
Hi, I just saw this by chance now while looking for another issue which may already have been discussed here. I have a MoveIt compatible JointTrajectoryAction server in the [jaco-arm-pkgs](https://github.com/JenniferBuehler/jaco-arm-pkgs) repository, though I'm still testing it again (I last used it in 2014) in collaboration with a colleague who has access to the real arm at the moment. It still uses my own URDF model but that can be easily changed to the new URDF model(s) in this repository, just requires small changes. I'm planning to do this soon. Anyone welcome to help testing. The code for the real arm is currently in the kinova_dev branch in the folder [jaco_arm/jaco_kinova](https://github.com/JenniferBuehler/jaco-arm-pkgs/tree/kinova_dev/jaco_arm/jaco_kinova), please also note the README.
I will keep you posted as soon as there are any updates on this.
