### ISSUE TITLE
Cartesian control through Gazebo

### ISSUE THREAD

**Issue by caiobarrosv** [Kinovarobotics/kinova-ros#125]
Hello,

I can only move Jaco arm in Gazebo using this topic

` '/effort_joint_trajectory_controller/command'`

When I try to run the following command nothing happens in Gazebo.
`rosrun kinova_demo pose_action_client.py -v -r j2n6s300 mdeg -- 0.01 0 0 0 10 10`

pose_action_client.py cannot be used to simulated in Gazebo?  
I am very new in ROS. 
Thank you in advance.

**Comment by martine1406** [comment]
Hi @caiobarrosv 

No pose_action_client.py can only be used to send commands to the real robot
Regards

Martine

**Comment by caiobarrosv** [comment]
Thank you.

Caio.
