### ISSUE TITLE
Unstable model in gazebo

### ISSUE THREAD

**Issue by marooncn** [Kinovarobotics/kinova-ros#128]
In our recent competition about robot grasping, Kinova robot is used, the robot type is  j2n7s300. When I load the model in gazebo by inputing:
`roslaunch kinova_gazebo robot_launch.launch kinova_robotType:=j2n7s300 use_trajectory_controller:=false`
There is some error:
> Unable to set value [-nan -nan -nan] for key[size] 

Then I change the relevant .xacro file accroding [issue 103](https://github.com/Kinovarobotics/kinova-ros/issues/103) , and the robot is loaded successfully. But the model is unstable
![Unstable model](https://user-images.githubusercontent.com/29606478/37598052-179827d4-2bbc-11e8-8f1b-7e8a05851cde.gif)
By the way, my OS version is Ubuntu 16.06 and the corresponding ROS is Kinetic which is different with your test version, so I thought it's because the ROS version. But my partner met the same problem with ROS Indigo. Can you help me to check it?

**Comment by dcconner** [comment]
This may be related to an unnecessary collision box:
https://github.com/CNURobotics/kinova-ros/commit/b4717c2a46eea96398fb80a99092d57e87163af9 

See the cnu_mico branch on our repo.
