### ISSUE TITLE
How to control 2 JACO2 using one ros master

### ISSUE THREAD

**Issue by makeecat** [Kinovarobotics/kinova-ros#130]
`roslaunch kinova_bringup kinova_robot.launch kinova_robotType:=j2n6s300 kinova_robotName:=left kinova_robotSerial:=PJ00000001030703130
roslaunch kinova_bringup kinova_robot.launch kinova_robotType:=j2n6s300 kinova_robotName:=right kinova_robotSerial:=PJ00000001030703133`

I tried to use my serial number and "Could not find the specified arm". I have tried the method that leaving kinova_robotSerial as blank or as 0, and I can control one arm in this way.

But how to control two arms?

**Comment by makeecat** [comment]
I solved this problem my update serial number by DevelopmentCenter. You need to modify robotName in control codes in this repository.

**Comment by hasauino** [comment]
I have the same problem. Can you please elaborate?
I have the serial number of each robot, however they are not found!

**Comment by makeecat** [comment]
Please flash the serial number of your robots in the DevelopmentCenter again. It is possible that these numbers are not flashed in!.

**Comment by hasauino** [comment]
Yes correct. It worked after I did this.
Thanks.
