### ISSUE TITLE
Wrist spins

### ISSUE THREAD

**Issue by kevincrawfordknight** [Kinovarobotics/kinova-ros#131]
Greetings, when I do

```
rosrun kinova_demo pose_action_client.py -v -r m1n4s200 mdeg -- 0 0 0.008 0 0 1
```

the wrist spins like crazy.  (I'm just trying to raise the arm 0.008m in the z direction).  How can I get x-y-z movement without the wrist spinning?

Thanks, 
Kevin

**Comment by martine1406** [comment]
Hi Kevin

Has you tried rosrun kinova_demo pose_action_client.py -v -r m1n4s200 mdeg -- 0 0 0.008 0 0 0?

**Comment by kevincrawfordknight** [comment]
Much better, thank you!
