### ISSUE TITLE
m1n4300 needs supporting files  

### ISSUE THREAD

**Issue by BladeWind** [Kinovarobotics/kinova-ros#137]
I have 2 4dof MICO2 arms with 3 finger grippers (m1n4300) that I would like working together. But I have found several missing files that I would need to get them working on ROS indigo.

These include:
kinova_control/config
kinova_control/launch
kinova_description/URDF
kinova_movieit/robot_configs

Will these arms be supported in this repository?

**Comment by martine1406** [comment]
Hi @BladeWind 
I think the best idea would be to genetare such files yourself based on what is available for MICO 6 dof (m1n6s300). The urdf is available [here](m1n4s200.xacro) (well almost... its the three finger version but I am sure you can figure out how to replace the gripper part with a three finger gripper based on the multiple examples you have in kinova_description/URDF. 

Let us know if you require any specific assistance. 
Thank you
Martine
