### ISSUE TITLE
Start a moveit demo without launching RViz

### ISSUE THREAD

**Issue by haudren** [Kinovarobotics/kinova-ros#138]
I am currently trying to run some tests on a remote machine that does not have a display attached. Everytime I run:
```
roslaunch j2s7s300_moveit_config virtual_robot_demo.launch
```

RViz is spawned, and crashes as there is no rendering context available. Could we add a switch to the launchers to avoid spawning any GUI? I'll try to submit a PR next week,

Thanks

**Comment by martine1406** [comment]
Hi @haudren

Ok perfect. I'll check you pull request. In short, you have to comment out the lines where Rviz is launched in the MoveIt launch files. It should be around [here](https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_moveit/robot_configs/j2s7s300_moveit_config/launch/j2s7s300_virtual_robot_demo.launch#L44)

Thanks
Martine
