### ISSUE TITLE
I have a series of path points, how should I control the manipulator？

### ISSUE THREAD

**Issue by zhaoxlvic** [Kinovarobotics/kinova-ros#144]
My manipulator model is m1n6s300.I now use my own planner not MOVEIT to get a series of path points. How should I control the manipulator? Send speed instruction or position instruction. Send position instructions, may appear the phenomenon of the carton. How can I calculate the speed of each point if it is sent in the form of speed。

**Comment by martine1406** [comment]
HI @zhaoxlvic

Everything good? Did you have more questions?

**Comment by zhaoxlvic** [comment]
HI @martine1406 
Thank you very much for your answer. My planner outputs path points in angular space. Now I send the angular velocity  to the robot. I have encountered some strange problems. I send 1 command every 10 ms. But ROS's time module is inaccurate，resulting in a deviation between the real position and the desired position.
For example, when I send a command and print the current time. Time will jump.
0.01s , 0.02, 0.03, 0.04, 0.05, 0.09, 0.10, 0.11, 0.12 ........
My system is ubuntu16.04, ROS is Kinetic. When I replace a new computer, this problem will not appear.
Thank you.

**Comment by martine1406** [comment]
ok good luck with all that
