### ISSUE TITLE
Finger velocity control

### ISSUE THREAD

**Issue by Achllle** [Kinovarobotics/kinova-ros#151]
Is it possible to send velocity commands to the fingers? There is a topic `$MODEL$_driver/in/joint_velocity` but there only seems to be an action service for the gripper.

**Comment by martine1406** [comment]
Hi @Achllle 

The Kinova API supports it (meaning the sendBasicTrajectory and sendAdvanceTrajectory functions in src/kinova_api.cpp. However, you might need to modify the $MODEL$_driver/in/joint_velocity topic (kinova_msgs::JointVelocity message) and the jointVelocityCallback in [src/kinova_arm.cpp](https://github.com/Kinovarobotics/kinova-ros/blob/c89b4ba71438b3bde4f007d470a30d7dfb579e38/kinova_driver/src/kinova_arm.cpp#L305)
