### ISSUE TITLE
what does SetForceControlParams.srv do?

### ISSUE THREAD

**Issue by sjhansen3** [Kinovarobotics/kinova-ros#156]
This service has the following parameters:

can you explain what they do?

geometry_msgs/Vector3 inertia_linear
geometry_msgs/Vector3 inertia_angular
geometry_msgs/Vector3 damping_linear
geometry_msgs/Vector3 damping_angular
geometry_msgs/Vector3 force_min_linear
geometry_msgs/Vector3 force_min_angular
geometry_msgs/Vector3 force_max_linear
geometry_msgs/Vector3 force_max_angular

**Comment by nsaif-kinova** [comment]
Hello Stephen,
I have attached a picture to better explain these parameters.
Modifications of these parameters will make your arm more or less responsive.
![forcecontrol](https://user-images.githubusercontent.com/35464719/43718362-6a58c7d0-9958-11e8-9187-fd6ccce94ef3.png)
