### ISSUE TITLE
Error : Could not find the required component 'moveit_core'

### ISSUE THREAD

**Issue by melvinma** [Kinovarobotics/kinova-ros#159]
Hi, I am new to Kinova ROS. I wonder if you could help me find out why I got the following error. Thanks.

Steps I did:
  1. install ros on ubuntu 18.04 through apt-get;
  2. install Kinova ROS following the following steps:

```
cd ~/robot_space/catkin_ws/src
git clone https://github.com/Kinovarobotics/kinova-ros.git kinova-ros
cd ~/robot_space/catkin_ws
catkin_make
```
Thanks for the help.
--------

-- Using CATKIN_DEVEL_PREFIX: /home/<USER>/robot_space/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.15", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/<USER>/robot_space/catkin_ws/build/test_results
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.15") 
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.14
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 14 packages in topological order:
-- ~~  - kinova_bringup
-- ~~  - kinova_control
-- ~~  - kinova_gazebo
-- ~~  - kinova_msgs
-- ~~  - kinova_driver
-- ~~  - kinova_arm_moveit_demo
-- ~~  - kinova_demo
-- ~~  - j2n6s300_ikfast
-- ~~  - j2s7s300_ikfast
-- ~~  - m1n6s300_ikfast
-- ~~  - kinova_description
-- ~~  - j2n6s300_moveit_config
-- ~~  - j2s7s300_moveit_config
-- ~~  - m1n6s300_moveit_config
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'kinova_bringup'
-- ==> add_subdirectory(kinova-ros/kinova_bringup)
-- +++ processing catkin package: 'kinova_control'
-- ==> add_subdirectory(kinova-ros/kinova_control)
-- +++ processing catkin package: 'kinova_gazebo'
-- ==> add_subdirectory(kinova-ros/kinova_gazebo)
-- +++ processing catkin package: 'kinova_msgs'
-- ==> add_subdirectory(kinova-ros/kinova_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Generating .msg files for action kinova_msgs/ArmJointAngles /home/<USER>/robot_space/catkin_ws/src/kinova-ros/kinova_msgs/action/ArmJointAngles.action
-- Generating .msg files for action kinova_msgs/ArmPose /home/<USER>/robot_space/catkin_ws/src/kinova-ros/kinova_msgs/action/ArmPose.action
-- Generating .msg files for action kinova_msgs/Arm_KinovaPose /home/<USER>/robot_space/catkin_ws/src/kinova-ros/kinova_msgs/action/Arm_KinovaPose.action
-- Generating .msg files for action kinova_msgs/SetFingersPosition /home/<USER>/robot_space/catkin_ws/src/kinova-ros/kinova_msgs/action/SetFingersPosition.action
-- kinova_msgs: 35 messages, 12 services
-- +++ processing catkin package: 'kinova_driver'
-- ==> add_subdirectory(kinova-ros/kinova_driver)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'kinova_arm_moveit_demo'
-- ==> add_subdirectory(kinova-ros/kinova_moveit/kinova_arm_moveit_demo)
-- Could NOT find moveit_core (missing: moveit_core_DIR)
-- Could not find the required component 'moveit_core'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "moveit_core" with
  any of the following names:

    moveit_coreConfig.cmake
    moveit_core-config.cmake

  Add the installation prefix of "moveit_core" to CMAKE_PREFIX_PATH or set
  "moveit_core_DIR" to a directory containing one of the above files.  If
  "moveit_core" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  kinova-ros/kinova_moveit/kinova_arm_moveit_demo/CMakeLists.txt:9 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/<USER>/robot_space/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/<USER>/robot_space/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:320: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Base path: /home/<USER>/robot_space/catkin_ws
Source space: /home/<USER>/robot_space/catkin_ws/src
Build space: /home/<USER>/robot_space/catkin_ws/build
Devel space: /home/<USER>/robot_space/catkin_ws/devel
Install space: /home/<USER>/robot_space/catkin_ws/install
####
####
Invoking "make cmake_check_build_system" failed

**Comment by martine1406** [comment]
HI 

This package is compatible with ros indigo/ubuntu 14.04. Please install ros on an Ubuntu 14.04 machine and let us know if you still get errors.

Thank you
