### ISSUE TITLE
Add a proper license for the `kinova_bringup` package

### ISSUE THREAD

**Issue by alimuldal** [Kinovarobotics/kinova-ros#161]
Please consider giving the [`kinova_bringup` package](https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_bringup/package.xml#L19) an open-source license. Without a license, users won't be able to reproduce, modify, or redistribute this code without your explicit permission.

**Comment by alimuldal** [comment]
On a related note, please could you include the full license text for packages marked as "BSD"-licensed (e.g. https://github.com/Kinovarobotics/kinova-ros/issues/93). "BSD" isn't specific enough, since there are multiple different BSD licenses with slightly different terms.

**Comment by martine1406** [comment]
Hi

Please consider the following [license file](https://github.com/Kinovarobotics/kinova-ros/blob/master/LICENSE) that was added to the repository. The repo now features clearly a BSD 3-Clause license. Thank you

**Comment by alimuldal** [comment]
Thanks, much appreciated! Would you mind also updating the `package.xml` files that still contain `<license>TODO</license>`?

**Comment by martine1406** [comment]
I did it on the master branch. Thank you for letting us know
