### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by ojijinWang** [Kinovarobotics/kinova-ros#166]
In kinova-ros/kinova_demo/nodes/kinova_demo/robot_control_modules.py

def publishCatesianVelocityCommands(cartVel, duration_sec, prefix):
	topic_name = '/' + prefix + 'driver/in/cartesian_velocity'
	#publish joint torque commands
	pub = rospy.Publisher(topic_name, kinova_msgs.msg.PoseVelocity, queue_size=1)
	poseVelCmd = kinova_msgs.msg.PoseVelocity()
	poseVelCmd.twist_linear_x = cartVel[0];
	poseVelCmd.twist_linear_y = cartVel[1];
	poseVelCmd.twist_linear_z = cartVel[2];
	**poseVelCmd.twist_angular_x = cartVel[3];
	poseVelCmd.twist_angular_x = cartVel[4];
	poseVelCmd.twist_angular_x = cartVel[5];**

I think it should be 
	**poseVelCmd.twist_angular_x = cartVel[3];
	poseVelCmd.twist_angular__y_ = cartVel[4];
	poseVelCmd.twist_angular__z_ = cartVel[5];**

**Comment by Behery** [comment]
Hi @ojijinWang,
I just saw this coincidentally, and yes, it makes sense. Maybe you should make a pull request.
btw, Is this demo actually working for you (the linear velocity at least)?

**Comment by martine1406** [comment]
yes this makes sense. thanks for pointing that out. I corrected that in the master branch version.
