### ISSUE TITLE
Is ethernet with ROS supported

### ISSUE THREAD

**Issue by sjhansen3** [Kinovarobotics/kinova-ros#175]
I see the documentation says 
"Note - Although this release supports Ethernet connection, this feature is only limited to test clients. Kinova will notify all users when Ethernet support is released for all customers."

Is this documentation up to date? 

Can you elaborate a little on the method of using ethernet? We tried following the following instructions:

    Setup a static IP address for your ethernet network say - 192.168.100.100
    With the robot connected to your PC via USB open kinova's Develepment Center
    Open tab General/Ethernet - Set robot IP Address to something like - 192.168.100.xxx
    Make sure MAC address is not all zero. If so contact support@kinova.ca
    Press 'Update' and restart robot
    In a terminal ping your robot's IP, your robot is setup for ethernet

To connect to robot via ethernet in ROS just set these parameters in robot_parameters.yaml -

connection_type: ethernet  
local_machine_IP: [your PC network IP]  
subnet_mask: [your network subnet mask]  

Can you elaborate on these steps?

After completing theses steps - the serial number never came up in the development center. We saw the serial number when connected through USB but after switching to Ethernet it disappeared and never came up again.

**Comment by martine1406** [comment]
Hi @sjhansen3 

There are a certain number of steps to enable the Ethernet connection with the robot. First of all, your arm needs a MAC address. If you connect your robot to the Development Center and click on Ethernet in General Settings. If you see a MAC address that is all zero, it means that your robot does not have a MAC address yet, and you have to contact support@kinova.ca to get one (please specify your robot's serial number). 

Then, the instructions are in the [SDK user guide](https://www.kinovarobotics.com/sites/default/files/SDK-UG-INT-EN%20201804-1.0%20%28KINOVA%E2%84%A2%20Software%20development%20kit%20user%20guide%29_2.pdf), at p. 21 mainly.

Please try the Ethernet connectivity on the Development Center first, then you can test it on ROS but specifying the parameters below in robot_parameters.yaml 

connection_type: ethernet
local_machine_IP: [your PC network IP]
subnet_mask: [your network subnet mask]

Those configurations tell the ROS package to use the Ethernet connection with the configuration local_machine_IP and subnet_mask on your computer side. 

I hope it is clearer
Martine
