### ISSUE TITLE
Gazebo immdietely crashed due to [gazebo_gui-2] process has died [pid 11076, exit code 134]

### ISSUE THREAD

**Issue by mambawockeez** [Kinovarobotics/kinova-ros#180]
Hi, im new to ros and kinova. And right now im trying to run a simulation for a kinova arm, the installation are complete. but when i try to run the command in the tutorial: **_roslaunch kinova_gazebo robot_launch.launch kinova_robotType:=j2n6s300_**, Gazebo immediately crushed. And here is the meesage in my terminal:
[INFO] [1541708946.105803, 0.363000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1541708946.114837314, 0.363000000]: Physics dynamic reconfigure ready.
[urdf_spawner-3] process has finished cleanly
log file: /home/ruxuan/.ros/log/8c84df30-e393-11e8-8743-f828197a2a1f/urdf_spawner-3*.log
Error [Param.cc:451] Unable to set value [-nan -nan -nan] for key[size]
gzclient: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreNode.cpp:630: virtual void Ogre::Node::setScale(const Ogre::Vector3&): Assertion `!inScale.isNaN() && "Invalid vector supplied as parameter"' failed.
[ INFO] [1541708946.529583490, 0.363000000]: Loading gazebo_ros_control plugin
[ INFO] [1541708946.529739830, 0.363000000]: Starting gazebo_ros_control plugin in namespace: j2n6s300
[ INFO] [1541708946.530595959, 0.363000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
Aborted (core dumped)
[ WARN] [1541708946.638724711, 0.363000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'j2n6s300_joint_1'.
[ WARN] [1541708946.639499150, 0.363000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'j2n6s300_joint_2'.
[ WARN] [1541708946.640085001, 0.363000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'j2n6s300_joint_3'.
[ WARN] [1541708946.640617219, 0.363000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'j2n6s300_joint_4'.
[ WARN] [1541708946.641398961, 0.363000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'j2n6s300_joint_5'.
[ WARN] [1541708946.642482700, 0.363000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'j2n6s300_joint_6'.
[ WARN] [1541708946.643513221, 0.363000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'j2n6s300_joint_finger_1'.
[ WARN] [1541708946.644006200, 0.363000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'j2n6s300_joint_finger_2'.
[ WARN] [1541708946.644392641, 0.363000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'j2n6s300_joint_finger_3'.
[ INFO] [1541708946.648647440, 0.363000000]: Loaded gazebo_ros_control.
[gazebo_gui-2] process has died [pid 11076, exit code 134, cmd /home/ruxuan/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/gzclient __name:=gazebo_gui __log:=/home/ruxuan/.ros/log/8c84df30-e393-11e8-8743-f828197a2a1f/gazebo_gui-2.log].
log file: /home/ruxuan/.ros/log/8c84df30-e393-11e8-8743-f828197a2a1f/gazebo_gui-2*.log
[INFO] [1541708946.904319, 0.609000]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1541708946.905707, 0.610000]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1541708946.907245, 0.612000]: Loading controller: effort_joint_trajectory_controller
[INFO] [1541708947.093137, 0.805000]: Loading controller: effort_finger_trajectory_controller
[INFO] [1541708947.184208, 0.897000]: Loading controller: joint_state_controller
[INFO] [1541708947.190374, 0.903000]: Controller Spawner: Loaded controllers: effort_joint_trajectory_controller, effort_finger_trajectory_controller, joint_state_controller
[INFO] [1541708947.192410, 0.905000]: Started controllers: effort_joint_trajectory_controller, effort_finger_trajectory_controller, joint_state_controller
[command_robot_home_pose-6] process has finished cleanly
log file: /home/ruxuan/.ros/log/8c84df30-e393-11e8-8743-f828197a2a1f/command_robot_home_pose-6*.log
^C[robot_state_publisher-5] killing on exit
[j2n6s300/j2n6s300_trajectory_controller-4] killing on exit
[gazebo-1] killing on exit
[INFO] [1541708954.896753, 8.414000]: Shutting down spawner. Stopping and unloading controllers...
[INFO] [1541708954.897011, 8.414000]: Stopping all controllers...
[gazebo-1] escalating to SIGTERM
[j2n6s300/j2n6s300_trajectory_controller-4] escalating to SIGTERM
[WARN] [1541708969.926831, 8.414000]: Controller Spawner error while taking down controllers: transport error completing service call: receive_once[/j2n6s300/controller_manager/switch_controller]: unexpected error [Errno 4] Interrupted system call
shutting down processing monitor...
... shutting down processing monitor complete
done
![screenshot from 2018-11-08 15-45-56](https://user-images.githubusercontent.com/26910282/48226307-688fe000-e36d-11e8-8b8c-88a869d1fc8f.png)

Anyone know how to solve this issue? Thnaks a lot!

**Comment by martine1406** [comment]
are you still on Ubuntu 14.04/ROS Indigo?
Have you installed the required packages on page https://github.com/Kinovarobotics/kinova-ros/wiki/Gazebo
Have you tried looking on the internet and on Gazebo forums to try to solve this issue?
