### ISSUE TITLE
URDF Lacking Inertial Elements

### ISSUE THREAD

**Issue by jcoll44** [Kinovarobotics/kinova-ros#182]
I'm trying to simulate the m1n6s300 arm in a simulation using a URDF file I generated using the XACRO. The arm contains two links, root and m1n6s300_end_effector, which don't contain inertial properties and as such create issues when simulating the arm. Are these links required for anything? And if not are they able to be removed?

**Comment by martine1406** [comment]
Hi

In my view, those links are required, especially the end_effector one. What kind of problem do you get? If you want to modify the urdf file on your end, you're free to go :-)

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over 2 years, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
