### ISSUE TITLE
Is Gen3 Ultra lightweight robot supported?

### ISSUE THREAD

**Issue by bringBackm** [Kinovarobotics/kinova-ros#186]
Hi all, we would like to buy the Gen3 Ultra lightweight robot and use it under ROS for researches.
So.. is the arm supported now? And we also would like to use the camera directly under ROS, it is feasible now..or..When?
Thank you.

**Comment by nsaif-kinova** [comment]
Hello bringBackm,
Thank you for your interest in Gen3, at the moment the arm is still under verification and validation, the ROS package will be released soon, we are planning to release two ROS packages, one for Gen3 and one for the cameras (they will be part of Kortex).
Sincerely,

**Comment by bringBackm** [comment]
Great to hear that!
Thanks!

**Comment by thieraufc** [comment]
Hello @nsaif-kinova -- can you offer an update as to when the packages, particularly the Gazebo files, will be released?

**Comment by nsaif-kinova** [comment]
Hello Chris,
For Gen3 ROS package you can refer to this link : https://github.com/Kinovarobotics/ros_kortex
However MoveIt and Gazebo files will be added soon but I don't have currently the exact date.
Sincerely,

**Comment by thieraufc** [comment]
Ok, thanks for your help!
