### ISSUE TITLE
[catkin_make failed] error: cannot convert ‘moveit::planning_interface::MoveItErrorCode’ to ‘bool’ in assignment

### ISSUE THREAD

**Issue by HappySamuel** [Kinovarobotics/kinova-ros#190]
Ubuntu Version: 16.04
ROS Version: Kinetic

I have been following the instruction of installation as below:
**cd ~/catkin_ws/src
git clone https://github.com/Kinovarobotics/kinova-ros.git kinova-ros
cd ~/catkin_ws
catkin_make**

However these errors (all are same) pops out and catkin_make failed. Is there any solution to this? Here i attached the picture of error.
![error_kinova_ros_installation](https://user-images.githubusercontent.com/18137963/49624001-cf56f680-fa0a-11e8-8b6c-7cbabee1d7a4.png)

**Comment by samuelhovington** [comment]
Hi Samuel,
Kinova does not officially support ros package for Jaco2 on kinetic.
But a collaborator develop a kinetic version of ros package.
Pull the master branch, then switch to commit 94c25e1. 
The steps should look like : 
`cd ~/catkin_ws/src
git clone https://github.com/Kinovarobotics/kinova-ros.git kinova-ros
git checkout master 
git checkout 94c25e1
cd ~/catkin_ws
catkin_make`
It works fine on our side, please let us know if it does not work.

Sincerely,

**Comment by HappySamuel** [comment]
I followed your instructions and tried. However it still failed to catkin_make. Here I attach the new error that pops out:

![error_catkin_make_kinova_ros](https://user-images.githubusercontent.com/18137963/49679985-90887580-faca-11e8-8cf3-2382047c3a24.png)

**Comment by martine1406** [comment]
have you installed moveit (required)? Please see https://github.com/Kinovarobotics/kinova-ros#moveit. You need to install the kinetic version of the packages in your case.

**Comment by HappySamuel** [comment]
Thank you to @martine1406  & @samuelhovington 

After followed instructions from both of you, the **"catkin_make"** is finally succeed. I believe these are the correct steps for **"catkin_make"** on **ROS Kinetic**:

**Pre-requisties**
(1) sudo apt-get install ros-kinetic-moveit
(2) sudo apt-get install ros-kinetic-trac-ik

**Installation**
(1) cd ~/catkin_ws/src
(2) git clone https://github.com/Kinovarobotics/kinova-ros.git kinova-ros
(3) cd kinova-ros
(4) git checkout master 
(5) git checkout 94c25e1
(6) cd ~/catkin_ws
(7) catkin_make

Then it will be successful.
