### ISSUE TITLE
 Finger Positions using Low-Level API while doing Torque Control

### ISSUE THREAD

**Issue by vinaysriram** [Kinovarobotics/kinova-ros#194]
Sorry for the delayed follow-up. Is there some example code supporting this? I am looking at lines 1328 to lines 1412 of this file: [https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_driver/src/kinova_comm.cpp]. Here, the allowed control modes are cartesian and angular, and the positions of the fingers are set through the `sendBasicTrajectory`API call. Is there a way to use the functions defined in [https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_driver/src/kinova_api.cpp] to set the finger positions while controlling Torques?

Thank you for your help.

_Originally posted by @vinaysriram in https://github.com/Kinovarobotics/kinova-ros/issues/189#issuecomment-447453614_

**Comment by martine1406** [comment]
Please see original issue.
