### ISSUE TITLE
Tutorial for the control  of Kinova arm J2s6s300 using Logitech Extreme 3D Pro Joystick

### ISSUE THREAD

**Issue by sakthiprasasd** [Kinovarobotics/kinova-ros#196]
Hi,
     Anyone can give the tutorial for the control of Kinova arm J2s6s300 using Logitech Extreme 3D Pro Joystick in ROS background.

**Comment by nsaif-kinova** [comment]
Hello Sakthiprasasd,
This joystick is used on Movo, please refer to this link : https://github.com/Kinovarobotics/kinova-movo/tree/master/movo_robot/movo_bringup/launch/teleop
