### ISSUE TITLE
Camera interfacing with Kinova J2s6s300

### ISSUE THREAD

**Issue by sakthiprasasd** [Kinovarobotics/kinova-ros#197]
Hi,
          We are trying to integrate the camera with the Kinova robotic arm J2s6s300,  for the awareness of the environment and automation. Can we use USB port in the Kinova base (USB host port -not used) for the camera feed? If I can use that port, How I access the camera using PC or desktop?

**Comment by nsaif-kinova** [comment]
Hello Sakthiprasasd,
Unfortunately you can not use the usb port for the camera feed, but you can use the expansion lines and get the signal from the joystick port, please refer to page 27-28 in the following document : https://www.kinovarobotics.com/sites/default/files/ULWS-RA-JAC-UG-INT-EN%20201804-1.0%20%28KINOVA%E2%84%A2%20Ultra%20lightweight%20robotic%20arm%20user%20guide%29_0.pdf

**Comment by sakthiprasasd** [comment]
Hi Nassif,
               Sorry for the separate message, In the user guide, mentioned as a 'Y' cable is supplied with the robot to allow you to access both the joystick and the expansion lines"  but we did not get any Y cable with Kinova suitcase. Can you please confirm the  Y cable is with J2s6s300 Kinova arm box???

**Comment by nsaif-kinova** [comment]
Hello sakthiprasasd,
To access the signal form the controller you have to use the expansion lines as mentioned before.
The Y cable is not shipped by default, please contact support@kinova.ca to get a Y cable.
Sincerely,

**Comment by nsaif-kinova** [comment]
It depends on your application, please note that the expansion lines on Jaco 2 only support analog camera, to use a digital one it needs to be wired from outside the arm.
We now have Gen3 with an embeded 3d depth and RGB camera, for more info please visit : https://www.kinovarobotics.com/en/products/robotic-arms/gen3-ultra-lightweight-robot

**Comment by sakthiprasasd** [comment]
Hi Nassif,
                We already have arm J2s6s300. Is it possible to purchase the camera used in the Gen3 separately?
If it is possible, can you send me a quotation for the same to my mail id: sakthiprasad221914@gmail.com

**Comment by nsaif-kinova** [comment]
Hello Sakthiprasasd,
This was answered by sales.
Thank you
