### ISSUE TITLE
joystick is not stabilising and we can not able to control the kinova arm J2s6s300

### ISSUE THREAD

**Issue by sakthiprasasd** [Kinovarobotics/kinova-ros#199]
Hi,
     The joystick is not stabilizing (continuously blinking green LED's) after switch on the Kinova arm J2s6s300. We cannot able to control the arm using joystick and SDK. Please help

**Comment by nsaif-kinova** [comment]
Hello,
This is for ROS related problems, please contact support@kinova.ca (include your arm serial number) to help you solve this problem.
Sincerely,

**Comment by sakthiprasasd** [comment]
Hi Nassif,
               we control using windows, not with ROS.
