### ISSUE TITLE
Getting admittance control working with Jaco 1?

### ISSUE THREAD

**Issue by skasewa** [Kinovarobotics/kinova-ros#207]
Not really an issue, but more a question for the community:

Jaco-1 does not have torque sensors, and so start_force_control and Torque Control do not do anything. Is there anybody here who has developed a solution to have similar functionality for the Jaco-1?

Essentially, I'm looking for a way to move the arm around, while recording what the sensors detect as positions / velocities while I'm doing this.

Do let me know. Any code implementations would be much appreciated. Thanks.

**Comment by felixmaisonneuve** [comment]
Unfortunately no. Since there is no torque sensors, it is not possible to control the arm manually
