### ISSUE TITLE
Mico arm shaking after closing gripper, knocks the target away

### ISSUE THREAD

**Issue by jingxixu** [Kinovarobotics/kinova-ros#208]
Hi, please see the video: https://youtu.be/u0kqAdf3N2c.

I am trying to use the mico arm to pick up the target block. After closing the gripper, the arm starts shaking and eventually knocks the target block away. I tried modifying how close the fingers should be and also tried different block masses and frictions but they do not help. 

Thanks!

**Comment by nsaif-kinova** [comment]
Hello Jingxi Xu,
Unfortunately we are not Gazebo experts.
Can you please check issue https://github.com/Kinovarobotics/kinova-ros/issues/157
https://github.com/Kinovarobotics/kinova-ros/issues/157#issuecomment-415310156

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a year, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
