### ISSUE TITLE
Weird invalid goal in moveit

### ISSUE THREAD

**Issue by jingxixu** [Kinovarobotics/kinova-ros#213]
I am using m1n6s200 to grasp a block. MoveIt! reports "Unable to sample any valid states for goal tree" when I try to manually set a goal using the interactive marker which is shown in the following screenshots. There is clearly no collision but I do not understand why the goal is invalid. I have spent many days on this and cannot figure out why. A good grasp needs to be very close to the target so that I have to move the arm there but MoveIt is preventing me from doing that. Can you guys help? Thanks!

![moveit2](https://user-images.githubusercontent.com/15113241/52667113-04396b00-2ede-11e9-8923-8fc1105ce8f9.png)
![moveit](https://user-images.githubusercontent.com/15113241/52667114-04396b00-2ede-11e9-9fd2-5ceef89d8aa2.png)
![terminal](https://user-images.githubusercontent.com/15113241/52667170-203d0c80-2ede-11e9-9360-3dc5546478be.png)

**Comment by nsaif-kinova** [comment]
Hello Jingxi,
Can you please tell me what version of ROS you are using? is it Kinetic or Indigo?
Currently we officially support ROS Indigo
Sincerely,

**Comment by jingxixu** [comment]
Hi, 

I am using ROS Kinetic. Do you think it is a ROS version problem? Is it possible to have some quick fixes?

Thanks!

**Comment by nsaif-kinova** [comment]
Hello Jingxi,
Sorry for the delay, Yes this might be the cause of your problem since the kinetic package was not officially developed and tested by Kinova.
Can you please try with ROS Indigo? On my side moveit with Indigo is working fine.
Sincerely,

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a year, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
