### ISSUE TITLE
moving just the end effector/ inverse kinematics

### ISSUE THREAD

**Issue by avpai** [Kinovarobotics/kinova-ros#214]
Hi,
I am new to ROS (ROS kinetic) and I have been playing with this library. My end goal is to move the end effector to the input position (let the inverse kinematics control the rest of the joints). I have been looking into move_robot.py. Sadly, the robot doesn't move unless I append some value to the velocity,acceleration,effort,etc. Is there any way where I can just give co-ordinates to the end effector and control the robot using inverse kinematics? Even a Rviz/gazebo simulation would be fine. Any suggestions and help would be greatly appreciated.

**Comment by nsaif-kinova** [comment]
Hello,
Please note we officially support ROS Indigo.
For joint position control please refer to : https://github.com/Kinovarobotics/kinova-ros#joint-position-control
For Cartesian position control (positions on the end effector) please refer to : https://github.com/Kinovarobotics/kinova-ros#cartesian-position-control
For Moveit : https://github.com/Kinovarobotics/kinova-ros/wiki/MoveIt
For Gazebo : https://github.com/Kinovarobotics/kinova-ros/wiki/Gazebo
Sincerely,

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a year, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
