### ISSUE TITLE
Actuating Gripper in Torque Control Mode

### ISSUE THREAD

**Issue by vinaysriram** [Kinovarobotics/kinova-ros#215]
Following up on the previous issue - yes, we are actually using the high-level API (the one given in [https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_driver/src/kinova_api.cpp]) . Using this API, the provided code does not seem to be working - specifically, the arm does not seem to respond to joystick commands sent from the emulated joystick. 

We are using a Kinova Mico with 2-finger gripper. Is there anything specific for initialization that is missing from the above code?

Furthermore, is there documentation that describes how set the fields of a JoystickCommand for particular actions? Thanks very much for your time.

_Originally posted by @vinaysriram in https://github.com/Kinovarobotics/kinova-ros/issues/189#issuecomment-467547551_

**Comment by nsaif-kinova** [comment]
Please refer to https://github.com/Kinovarobotics/kinova-ros/issues/189#issuecomment-467622040
