### ISSUE TITLE
The finger_1 of the 3finger gripper is not correctly assembled. 

### ISSUE THREAD

**Issue by xuhuairuogu** [Kinovarobotics/kinova-ros#217]
The finger_1 is wrongly assembled. Maybe the orientation should be modified.
![image](https://user-images.githubusercontent.com/10009476/53881289-36387b80-400b-11e9-8b43-0a5786bdd311.png)

**Comment by nsaif-kinova** [comment]
Hi,
Can you explain a bit more, what do you mean by wrongly assembled, which one is the finger 1?
Did you use our URDF files?
Sincerely,

**Comment by xuhuairuogu** [comment]
Yeah. I just used the kinova-ros package. I have display the j2n6s300 model in rviz, gazebo and vrep, all of which shows that the axis of finger 1(the right one in the above picture) does not align with the axis of the palm.

**Comment by nsaif-kinova** [comment]
Hello xuhuairuogu,
Can you please send me a picture of the real gripper highlighting the error you see?
Sincerely,

**Comment by xuhuairuogu** [comment]
I do not have a real robot at hand. All is based on the observation in simulation. I think the value of the finger 1's rotation parameters  should be modified. My environment is Ubuntu16.04 + ROS KInetic + gazebo 7.14.0 + vrep 3.6.0

**Comment by xuhuairuogu** [comment]
![image](https://user-images.githubusercontent.com/10009476/53898664-6d6d5380-4030-11e9-8e8a-b6e5c2e892fe.png)

**Comment by nsaif-kinova** [comment]
Hello xuhuairuogu,
We officially support ROS indigo branch for Gen2, the URDF model of the fingers I believe is correct, but I will take in consideration your comments.
For more information about our Gen2 please refer to this link https://www.kinovarobotics.com/en/knowledge-hub/gen2-ultra-lightweight-robot
where you can find the user's guide, the CAD model and many more information.
Sincerely,

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a year, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
