### ISSUE TITLE
world link defined in URDF/Xacro and SRDF

### ISSUE THREAD

**Issue by christian-rauch** [Kinovarobotics/kinova-ros#220]
The URDF/Xacro files define the `world` link as the root of the kinematic chain, which is connected via `connect_root_and_world` to the actual root of the robot kinematic chain (frame `root`).
The SRDF defines a virtual joint `world_joint` with the same connection.

Taking both joints into account, this is not a kinematic tree anymore since there are two paths from `world` to `root`. Consequently it can cause issues when determining the root for planning. See also: https://github.com/ros-industrial/universal_robot/issues/347 and https://github.com/ros-industrial/universal_robot/pull/284.

**Comment by sbrisebois** [comment]
Hi Christian,

Thank you for you work. 
I will have a look to your PR very soon. I have to investigate if this does not  broke demos and other development with the package.

Sincerely,
Sylvain Brisebois
