### ISSUE TITLE
Speech Based point to point control of Kinova Jaco 2 Robot Arm

### ISSUE THREAD

**Issue by saravanan1480** [Kinovarobotics/kinova-ros#223]
Dear Sir/Madam,
I want to control Kinova Jaco 2 Robot Arm[j2n6s300] using speech. My speech recognition is working fine and it is publishing the text as lm_data. I have subscribed to lm_data and Now for the control Part, I want to move each joint from its initial position to its final position.
For example, if I say "ROTATE BASE CLOCKWISE", only BASE joint should move from one position to another and if I say "ROTATE BASE ANTI CLOCKWISE", only BASE joint should move vice-versa.
Similarly, if I say "MOVE ELBOW UP" only third joint should move from one position to another and if I say "MOVE ELBOW DOWN" only third joint should move vice-versa.

As stated earlier, I have subscribed to lm_data where I am getting text form of speech. But I am unaware of what angles I need to publish for each joint and where I need to publish. I have tried to publish with Kinova_msgs/ArmJointAnglesGoal, but all in vain.
Is there any possibility that I can actuate only one Joint at a time?
What maximum and minimum angles  I need to specify for each joint of kinova robot arm [j2n6s300]?
How to publish my joint angles? Is kinova_msgs/ArmJointAnglesGoal right to publish?

**Comment by nsaif-kinova** [comment]
Hello Saravanan,
To send joint positions please refer to this example : https://github.com/Kinovarobotics/kinova-ros#joint-position-control
To send joint velocities please refer to this link : https://github.com/Kinovarobotics/kinova-ros#velocity-control-for-joint-space-and-cartesian-space
The minimum angles to send depend on the PID and error filter applied on the arm, you can start with few degrees it should be fine.
Please let me know if you need more information.
Sincerely,

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a year, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
