### ISSUE TITLE
roslaunch kinova_bringup kinova_robot.launch failed

### ISSUE THREAD

**Issue by xuhuairuogu** [Kinovarobotics/kinova-ros#224]
I have got a new Jaco these days. I have installed JACO2SDK on Ubuntu16.04 successfully, connected Jaco and Ubuntu by USB and it is OK to control the robot by pressing the buttons in the Angular Control tab.So, I think there is no problem with communication and driver. Then, I copied the 10-kinova-arm.rules file to /etc/udev/rules.d directory. However, when I try to control Jaco through kinova_ros package by the command 'roslaunch kinova_bringup kinova_robot.launch', something wrong goes like the following:
![Screenshot from 2019-04-02 14-59-23](https://user-images.githubusercontent.com/10009476/55382337-fb692b00-5557-11e9-8e36-f14eca4bc12e.png)

**Comment by nsaif-kinova** [comment]
Hello,
Do you have the Dev center or Torque consol open when you try to launch ROS?
Please note Jaco2 can only connect to one interface, so Please close the Dev Center and Torque Console before you use ROS.
Sincerely,

**Comment by xuhuairuogu** [comment]
Yeah, I close both before launch

**Comment by xuhuairuogu** [comment]
It is OK after reboot Ubuntu
