### ISSUE TITLE
Difference between gravity compensation mode and addmitance control (without Cartesian/joint postion command))

### ISSUE THREAD

**Issue by ZhengYi0310** [Kinovarobotics/kinova-ros#226]
Is there any difference between gravity compensation mode and the admitance control mode (without Cartesian/joint position command), since according to the wiki, it looks like in both cases the arm can be manually moved.

Also, why the arm needs to move to the candle-like position between starting gravity compensation mode, can't the arm switch to gravity compensation mode from any pose as long as the base is mounted correctly (aligned with the default 0, 0, -9.81 gravity vector) ?

Thanks

**Comment by nsaif-kinova** [comment]
Hello,
Gravity compensation is for torque readings, using this you can get a reading of your torque values with the gravity compensated.

To better understand the difference between torque and admittance mode please refer to page 58-61 in this document : https://www.kinovarobotics.com/sites/default/files/ULWS-RA-JAC-UG-INT-EN%20201804-1.0%20%28KINOVA%E2%84%A2%20Ultra%20lightweight%20robotic%20arm%20user%20guide%29_0.pdf

More information about torque control are available on this link: [file:///C:/Program%20Files%20(x86)/JACO-SDK/GUI/html/TorqueDocumentationGeneral.html](url) (please download the SDK to have access https://drive.google.com/open?id=1UEQAow0XLcVcPCeQfHK9ERBihOCclkJ9)

More information about the admittance mode are available on this link : [file:///C:/Program%20Files%20(x86)/JACO-SDK/GUI/html/_kinova_8_a_p_i_8_usb_command_layer_ubuntu_8h_aedea2cbf905878c9b24d998e0fa3e06e.html#aedea2cbf905878c9b24d998e0fa3e06e](url)

The simple way to describe the difference is Torque control read the torque values to send torque commands, while Admittance mode read the torque values to send velocity commands.
Gravity compensation do not affect any of the two modes, but your gravity vector is very important to be set correctly.

The arm can switch to torque mode in any position if your torque is well calibrated, you should put it in candle like position to calibrate your torque, please refer to this question "My arm will not switch from position mode to torque mode"page 96 in the following document : https://www.kinovarobotics.com/sites/default/files/ULWS-RA-JAC-UG-INT-EN%20201804-1.0%20%28KINOVA%E2%84%A2%20Ultra%20lightweight%20robotic%20arm%20user%20guide%29_0.pdf
Sincerely,
