### ISSUE TITLE
How to move the end effector like a manipulator instructor in my code without first planning?

### ISSUE THREAD

**Issue by 920888890** [Kinovarobotics/kinova-ros#246]
Hi, I just want to know if there is an API that allows me to make the end effector approach the target pose like a manipulator instructor in my code。not like Moveit! In that case, I must first plan the path.
If anyone can help me, thank you very much！

**Comment by nsaif-kinova** [comment]
Hello,
Do you mean change the coordinates according to the end effector and not the base?
If yes please refer to this https://github.com/Kinovarobotics/kinova-ros/issues/193
Sincerely,

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a year, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
