### ISSUE TITLE
Is the transformation among links correct?

### ISSUE THREAD

**Issue by Hubert51** [Kinovarobotics/kinova-ros#260]
## Description
I am trying to use tag to adjust the pose of arm. The camera is on the wrist. However, when I was running the code, the transformation from **base** to **end_effector** did not look like correct. The wrist always rotate 90 degree for each iteration
```
    rospy.init_node('tf2_goal_listener')
    tfBuffer = tf2_ros.Buffer()
    listener = tf2_ros.TransformListener(tfBuffer)
    rate = rospy.Rate(0.25)
    while not rospy.is_shutdown():
        try:
            trans = tfBuffer.lookup_transform('j2n6s300_link_base', 'j2n6s300_end_effector', rospy.Time())
        except (tf2_ros.LookupException, tf2_ros.ConnectivityException, tf2_ros.ExtrapolationException):
            rate.sleep()
            continue
        rate.sleep()
        position = [trans.transform.translation.x,trans.transform.translation.y,trans.transform.translation.z]
        orientation = [trans.transform.rotation.x,trans.transform.rotation.y,trans.transform.rotation.z,trans.transform.rotation.w]
        try:            
            result = cartesian_pose_client(position, orientation)
            print('Cartesian pose sent!')
        except rospy.ROSInterruptException:
            print "program interrupted before completion"
```
## Version

ROS distribution : kinetic

Branch and commit you are using : kinetic-dev

## Steps to reproduce
1. run the driver code
2. run the transformation code above

## Expected behavior
The position and orientation should not be changed. However, the orientation is changing every iteration. Did somebody have this question before? How should I check the transformation code since these code was not written by me?

**Comment by alexvannobel** [comment]
Hi @Hubert51 ,
Sorry for the delay.
I think the transformation code you sent is missing a part, because I get a 
``` NameError: name 'cartesian_pose_client' is not defined```
Can you provide the complete code so I can test your behaviour?

Thanks a lot,
Alex

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a year, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
