### ISSUE TITLE
melodic release

### ISSUE THREAD

**Issue by christian-rauch** [Kinovarobotics/kinova-ros#262]
## Summary

Binary release via bloom to ROS melodic repos

## Use case

A binary release allows to download the package via the package manager, wihtout adding it to a workspace and compile. Additionally, it marks the package as stable.

## Alternative

Compile from source on released/tagged git version.

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a year, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
