### ISSUE TITLE
How to use kinova in 18.04 Ubuntu？

### ISSUE THREAD

**Issue by BlakeQuan** [Kinovarobotics/kinova-ros#265]

**Comment by mpatalberta** [comment]
What version of ros are you using. I am running with ubuntu 18.04 with melodic.
I am using the masterbranch of kinova

**Comment by BlakeQuan** [comment]
> 你使用的是什么版本的ros。我正在使用带有旋律的ubuntu 18.04。
> 我正在使用kinova的masterbranch

I am using the jaco 2-6 of kinova and running with ubuntu 18.04 with melodic. Besides,I'm a beginner.

**Comment by alexvannobel** [comment]
Hi @BlakeQuan ,

Can you make sure you checked out the ```master``` branch? It works with Melodic. 
Apart from that, the error you have is a bit weird. Is your ROS Melodic installation correct?

Best,
Alex

**Comment by BlakeQuan** [comment]
After the update, the issue has been resolved
