### ISSUE TITLE
How to change joystick control

### ISSUE THREAD

**Issue by kurenaloha** [Kinovarobotics/kinova-ros#268]
I want to change the value that is actually input to the robot from the value that is input with the joystick.

I will send  the value of cartesian goals  to the robot action server.
What topic is the joystick value publised in?

**Comment by rsaif22** [comment]
Hi, did you find the answer to this?

**Comment by felixmaisonneuve** [comment]
Hi @rsaif22 

Joystick Value can be sent by the [SendJoystickCommand](https://github.com/Kinovarobotics/kinova-ros/blob/melodic-devel/kinova_driver/include/kinova/Kinova.API.USBCommandLayerUbuntu.h#L161) API function. 

It is currently not bind to any subscriber, but you can always change your kinova_arm.cpp driver to create your own topic and use it after

Best,
Felix
