### ISSUE TITLE
api access to get damping param: getCartesianInertiaDamping

### ISSUE THREAD

**Issue by LongfeiProjects** [Kinovarobotics/kinova-ros#273]
## Summary
API access to get damping parameters

## Use case
since we already had setCartesianInertiaDamping, it would be useful to have getCartesianInertiaDamping as well. This parameter is not in rosparam. Without knowing the default value, one is afraid to set it to a new value before knowing he can cover it back.

An alternative way is to put this value in a xml file, so that user can modify it freely. 

## Notes
I understand it may take time to put it in the future release. For now, could anyone tell me the default value for CartesianInertiaDaming?

**Comment by alexvannobel** [comment]
Hi Longfei,

Sorry for the delay. It's true that it will take time to add a function to get those parameters from the robot arm, so I retrieved them from the arm's firmware and the values are : 
- Jaco 6DOF Curved wrist : 
    - Damping: [18.18; 31.81; 54.55; 1.27; 1.27; 1.27]
    - Inertia: [6.36, 11.14; 13.64; 0.32; 0.32; 0.32]
- Jaco 6DOF Spherical wrist : 
    - Damping: [18.18; 31.81; 54.55; 6.82; 6.82; 6.82]
    - Inertia: [5.45, 9.55; 16.36; 2.05; 2.05; 2.05]
- Jaco 7DOF Spherical wrist : 
    - Damping: [9.09; 15.91; 27.27; 3.41; 3.41; 3.41]
    - Inertia: [2.73, 4.77; 8.18; 1.02; 1.02; 1.02]

If you mess up the values, you can always reboot the arm and the default values will be put back. 

Best,
Alex
