### ISSUE TITLE
movement of kinova in the direction of end effector for j2s6s300

### ISSUE THREAD

**Issue by pavanth** [Kinovarobotics/kinova-ros#294]
## Summary

We have attached the end effector to the 6th DOF of the kinova, and our intention is to move the kinova arm in the direction of the end effector
## Use case

To move the kinova arm in the direction of the end effector

## Alternative

Do you have an idea how on how best to implement this enhancement?
I have been trying this for a month. I think we have to modify the pose_action_client.py as we did for the tool coordinate

If this feature is not implemented, do you have a workaround?
I think its not 

## Possible issues

Anything that could be affected by the new feature?
I don’t think so.

**Comment by pavanth** [comment]
I would like to give more information about the end effector. This is the image:
![IMG_20191217_103146](https://user-images.githubusercontent.com/39085324/70966366-013c7780-20b9-11ea-91f7-410fd99774b0.jpg)

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a year, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
