### ISSUE TITLE
Acceleration and velocity control

### ISSUE THREAD

**Issue by pitergit95** [Kinovarobotics/kinova-ros#295]
Hi,

I would like to know, if there is possibility to control the acceleration of each joint in jaco arm.
Another thing, i tried to control the speed of each joint but it doesnt work. I have done it, in the way written in documentation. I mean, i created publisher like other publishers used for jaco arm. Also i checked, if frequency of send messages was 100 Hz. It doesnt work, even by sending direct terminal command. I wonder if there are some tips and tricks to make it work in proper way?

Thanks in advance for your help.

**Comment by polthergeist** [comment]
Hi @pitergit95 ,
It is not possible to control or change the joint acceleration but velocity control should work. When you say it is not working, is the joint not miving at all or is it jerky?

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a year, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
