### ISSUE TITLE
How to convert xacro file to urdf file?

### ISSUE THREAD

**Issue by yimingli1998** [Kinovarobotics/kinova-ros#298]
Hi, I use
rosrun xacro xacro --inorder model.urdf.xacro > model.urdf
to convert xacro file to urdf file, but the urdf file is blank.
How can I do to get the urdf file from j2n6s300.xacro?

**Comment by NexusReflex** [comment]
Use
rosrun xacro xacro j2n6s300_standalone.xacro > model.urdf

**Comment by gstlaurentkinova** [comment]
HI @yimingli1998,

Can you confirm if this fixed your issue ? 

Best,

Gabriel

**Comment by felixmaisonneuve** [comment]
I assume this issue has been resolved. I am closing it
