### ISSUE TITLE
kinova_interactive_control in launchfile

### ISSUE THREAD

**Issue by JorenFrans** [Kinovarobotics/kinova-ros#309]
Hey Everyone,

We are trying to make a launchfile that calls in the kinova_interactive_control node. We can't make it happen though and we don't know why. We tried the following options but always get the same error message:

```
<launch>
    <node name="kinova_control" pkg="kinova_driver" type="kinova_interactive_control">
        <param name="kinova_robotType" value="j2s6s200"/>
    </node>
</launch>
```

```
<launch>
   <node name="kinova_control" pkg="kinova_driver" type="kinova_interactive_control" args=”j2s6s200”>
   </node>
</launch>
```
We also tried without the robotType-parameter
The error message says:

![Screenshot from 2020-07-09 13-50-59](https://user-images.githubusercontent.com/34520419/87038017-6e4a6280-c1ed-11ea-9417-60afe9adb5bc.png)

Does anyone know what this message means or how to solve it?

Thanks in advance,
Joren

**Comment by alexvannobel** [comment]
Hi @JorenFrans ,

Weird error! I could reproduce on my end and it seems the `ros::init` function was not called first thing in the main and that caused the error.

After the modification, I could launch the node with your launch file.

The linked PR will close the issue when merged.

Best,
Alex
