### ISSUE TITLE
How to set soft joint limits ?

### ISSUE THREAD

**Issue by farmange** [Kinovarobotics/kinova-ros#315]
Hi everyone,

I there a way to set joint limit through ROS stack or C++ API ? 
In which component the position loop is implemented (KA actuator or Kinova controller) ? 

Thanks in advance!

**Comment by felixmaisonneuve** [comment]
Hi @farmange,
Unfortunately, it is not possible to set a joint range or a joint limit. Limits are set in the controller module that does the arm trajectory calculation. 
There is currently no way to set a high level limition via the API
