### ISSUE TITLE
Cartesian_workout doesn't work

### ISSUE THREAD

**Issue by hvpandya** [Kinovarobotics/kinova-ros#32]
I can subscribe to cartesian topics like tool_position but the cartesian workout just doesn't work. On the terminal it says Using the specified pose and Done but nothing happens to the real arm.

Everything else has worked perfectly so far except for this cartesian_workout.

Any hints on this one?

**Comment by francoisferland** [comment]
Which demo poses sequence did you try with cartesian_workout ? demo_pose_sequence_2.txt should go through 5 poses before stopping (and display them at the console).
