### ISSUE TITLE
MechanicalWorkOptimizationObjective

### ISSUE THREAD

**Issue by s265452** [Kinovarobotics/kinova-ros#363]
Hi everyone,
I'm using 

Distro: ROS Melodic
arm= kinova Jaco2 - 7 DoF robotType: js7s300
planner: ompl

My file ompl.yaml:

planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
    optimization_objective: MechanicalWorkOptimizationObjective
    range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
    longest_valid_segment_fraction: 0.05
    projection_evaluator: joints(j2s7s300_joint_1,j2s7s300_joint_2) #joints
    enforce_joint_model_state_space: true
  ESTkConfigDefault:
    type: geometric::EST
    optimization_objective: MechanicalWorkOptimizationObjective
    range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0 setup()
    goal_bias: 0.05  # When close to goal select goal, with this probability. default: 0.05
    enforce_joint_model_state_space: true
  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
    optimization_objective: MechanicalWorkOptimizationObjectiv
    range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
    border_fraction: 0.9  # Fraction of time focused on boarder default: 0.9
    min_valid_path_fraction: 0.5  # Accept partially valid moves above fraction. default: 0.5
    projection_evaluator: joints(j2s7s300_joint_1,j2s7s300_joint_2)
    enforce_joint_model_state_space: truee
  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
    optimization_objective: MechanicalWorkOptimizationObjective
    range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
    border_fraction: 0.9  # Fraction of time focused on boarder default: 0.9
    failed_expansion_score_factor: 0.5  # When extending motion fails, scale score by factor. default: 0.5
    min_valid_path_fraction: 0.5  # Accept partially valid moves above fraction. default: 0.5
    projection_evaluator: joints(j2s7s300_joint_1,j2s7s300_joint_2)
    enforce_joint_model_state_space: true
  KPIECEkConfigDefault:
    type: geometric::KPIECE
    optimization_objective: MechanicalWorkOptimizationObjective
    range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
    goal_bias: 0.05  # When close to goal select goal, with this probability. default: 0.05 
    border_fraction: 0.9  # Fraction of time focused on boarder default: 0.9 (0.0,1.]
    failed_expansion_score_factor: 0.5  # When extending motion fails, scale score by factor. default: 0.5
    min_valid_path_fraction: 0.5  # Accept partially valid moves above fraction. default: 0.5
    projection_evaluator: joints(j2s7s300_joint_1,j2s7s300_joint_2)
    enforce_joint_model_state_space: true
  RRTkConfigDefault:
    type: geometric::RRT
    optimization_objective: MechanicalWorkOptimizationObjective
    range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
    goal_bias: 0.05  # When close to goal select goal, with this probability? default: 0.05
    enforce_joint_model_state_space: true
  RRTConnectkConfigDefault:
    optimization_objective: MechanicalWorkOptimizationObjective
    type: geometric::RRTConnect
    range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
    enforce_joint_model_state_space: true
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    optimization_objective: MechanicalWorkOptimizationObjective
    range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
    goal_bias: 0.05  # When close to goal select goal, with this probability? default: 0.05
    delay_collision_checking: 1  # Stop collision checking as soon as C-free parent found. default 1
    enforce_joint_model_state_space: true #forza il pianificatore a pianificatore nello spazio giunti
  TRRTkConfigDefault:
    type: geometric::TRRT
    optimization_objective: MechanicalWorkOptimizationObjective
    range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
    goal_bias: 0.05  # When close to goal select goal, with this probability? default: 0.05
    max_states_failed: 10  # when to start increasing temp. default: 10
    temp_change_factor: 2.0  # how much to increase or decrease temp. default: 2.0
    min_temperature: 10e-10  # lower limit of temp change. default: 10e-10
    init_temperature: 10e-6  # initial temperature. default: 10e-6
    frountier_threshold: 0.0  # dist new state to nearest neighbor to disqualify as frontier. default: 0.0 set in setup() 
    frountierNodeRatio: 0.1  # 1/10, or 1 nonfrontier for every 10 frontier. default: 0.1
    k_constant: 0.0  # value used to normalize expresssion. default: 0.0 set in setup()
    enforce_joint_model_state_space: true
  PRMkConfigDefault:
    type: geometric::PRM
    optimization_objective: MechanicalWorkOptimizationObjective
    max_nearest_neighbors: 10  # use k nearest neighbors. default: 10
    enforce_joint_model_state_space: true
  PRMstarkConfigDefault:
    type: geometric::PRMstar
    optimization_objective: MechanicalWorkOptimizationObjective
    enforce_joint_model_state_space: true
PersistentLazyPRMstar: # use this with a representative environment to create a roadmap
    type: geometric::LazyPRMstar
    multi_query_planning_enabled: true
    store_planner_data: true
    load_planner_data: false
    planner_data_path: /tmp/roadmap.graph
    enforce_joint_model_state_space: true
PersistentLazyPRM: # use this to load a previously created roadmap
    type: geometric::LazyPRM
    multi_query_planning_enabled: true
    store_planner_data: false
    load_planner_data: true
    planner_data_path: /tmp/roadmap.graph
    enforce_joint_model_state_space: true
SemiPersistentLazyPRMstarkConfigDefault: # reuses roadmap during lifetime of node but doesn't save/load roadmap to/from disk
    type: geometric::LazyPRMstar
    multi_query_planning_enabled: true
    store_planner_data: false
    load_planner_data: false
    enforce_joint_model_state_space: true
SemiPersistentLazyPRMkConfigDefault: # reuses roadmap during lifetime of node but doesn't save/load roadmap to/from disk
    type: geometric::LazyPRM
    multi_query_planning_enabled: true
    store_planner_data: false
    load_planner_data: false
    enforce_joint_model_state_space: true
arm:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - PersistentLazyPRMstar
    - PersistentLazyPRM
    - SemiPersistentLazyPRMstarkConfigDefault
    - SemiPersistentLazyPRMkConfigDefault
gripper:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault

I wish set     optimization_objective: MechanicalWorkOptimizationObjective  at every planner but when I run my code I read :

[ INFO] [1635706076.154876695]: arm[TRRTkConfigDefault]: No optimization objective specified.  Defaulting to mechanical work minimization.

Where is the bug????

I also wish to save the roadmap created by PRM. How can I do that??
I tried to use these planners:

    - PersistentLazyPRMstar
    - PersistentLazyPRM
    - SemiPersistentLazyPRMstarkConfigDefault
    - SemiPersistentLazyPRMkConfigDefault

but I read something like this:

[ INFO] [1635707056.840641307]: Initializing OMPL interface using ROS parameters
[ERROR] [1635707056.846770703]: Could not find the planner configuration 'PersistentLazyPRMstar' on the param server
[ERROR] [1635707056.847301699]: Could not find the planner configuration 'PersistentLazyPRM' on the param server
[ERROR] [1635707056.847842067]: Could not find the planner configuration 'SemiPersistentLazyPRMstarkConfigDefault' on the param server
[ERROR] [1635707056.848230028]: Could not find the planner configuration 'SemiPersistentLazyPRMkConfigDefault' on the param server

Can You help me?
Thank you in advance

**Comment by felixmaisonneuve** [comment]
This was answered in issue #362
