### ISSUE TITLE
3 Finger gripper - Incorrect origin of the 1st finger

### ISSUE THREAD

**Issue by AndrejOrsula** [Kinovarobotics/kinova-ros#369]
## Description

Origin of the 1st finger in the 3-finger gripper has an incorrect origin. This issue has already been reported in https://github.com/Kinovarobotics/kinova-ros/issues/217 back in 2019 but it hasn't been resolved.

Below is the xacro line that causes the problem.

https://github.com/Kinovarobotics/kinova-ros/blob/3078ec6f00225e0ec5b80aae800bd3d94a59c369/kinova_description/urdf/kinova_finger_set.xacro#L25

## Version

ROS distribution : `rolling` (Irrelevant)

Branch and commit you are using : I believe this issue has always been present on all branches

## Expected behavior

3 Finger gripper should have the same kinematic configuration as the real robot, where `finger_1` and `finger_2` close towards each other to create a pinching grasp.

![Screenshot_20211130_172421](https://user-images.githubusercontent.com/22929099/144093197-9db9ade1-cbbd-4dcd-a804-f7db17397446.png)

## Actual behavior

The origin of `finger_1` is incorrect and it points more towards `finger_3` (top) than it should, as seen in the image below with the gripper closed.

![Screenshot_20211130_173242](https://user-images.githubusercontent.com/22929099/144094012-3b293f23-ab99-4126-9b52-9f1a1ece639d.png)

---

Even when using the rotation described in the comment above the xacro line (RPY `-1.5707963267948966 0.6492624817418906 1.7819811662862104`), the fingers still do not close properly as they should.

https://github.com/Kinovarobotics/kinova-ros/blob/3078ec6f00225e0ec5b80aae800bd3d94a59c369/kinova_description/urdf/kinova_finger_set.xacro#L24-L25

- **Left image**: Current version (pointing towards incorrect `finger_3`)
- **Right image**: Using `-1.5707963267948966 0.6492624817418906 1.7819811662862104`, `finger_1` points towards the correct `finger_2` but it is still wrong and the fingers do not close as they should.
<p align="center" float="middle">
  <img width="45.0%" src="https://user-images.githubusercontent.com/22929099/144094983-b2f3d071-6076-4170-ada8-c5454dafa2f1.png" alt="LEFT"/>
  <img width="45.0%" src="https://user-images.githubusercontent.com/22929099/144094996-122a4f62-2062-45d7-966e-b65859e929d1.png" alt="RIGHT"/>
</p>

**Comment by AndrejOrsula** [comment]
If someone wants to tackle this issue, [Kinova Gen2 Technical Resources](https://www.kinovarobotics.com/en/resources/gen2-technical-resources) contains link to download the CAD model (`STEP`). However, I do not know if the CAD model is correct.

**Comment by felixmaisonneuve** [comment]
Hi @AndrejOrsula,

Thank you for this very detailed issue. I understand when you say the first finger is closing towards the third finger, and this is true (and it should be fixed). 

However, I am not sure what you mean when you say that, even with the correct orientation, the finger is still wrong.
> finger_1 points towards the correct finger_2 but it is still wrong and the fingers do not close as they should

What is still wrong? Can you elaborate on that? 
I want to fully understand what you think should be the correct way to address this issue. If it is just a matther of changing fingers orientation, I can change it pretty quickly, but if the fix requires a "big" amount of work (like modifiying CAD files), it might take some time before I actually tackle this.

Best,
Felix

**Comment by AndrejOrsula** [comment]
Hello @felixmaisonneuve,

Thank you for your reply.

> However, I am not sure what you mean when you say that, even with the correct orientation, the finger is still wrong.
>
> >finger_1 points towards the correct finger_2 but it is still wrong and the fingers do not close as they should
>
> What is still wrong? Can you elaborate on that?

By "wrong", I mean that `finger_1` and `finger_2` do not create a properly aligned pinching grasp even when using orientation from the comment. In URDF, these two fingers are not opposing each other exactly as they are on the real robot (first image of real robot in the issue description).

Below is a small drawing of what I mean by "properly aligned". I believe that the desired behaviour would make `finger_1` and `finger_2` aligned in a way where they could touch along the entire length of the finger tip when closed, just as on the real robot.  

![](https://user-images.githubusercontent.com/22929099/144245659-78cad422-f794-4c3b-bf9c-d806355c8624.png)

---

> I want to fully understand what you think should be the correct way to address this issue. If it is just a matther of changing fingers orientation, I can change it pretty quickly, but if the fix requires a "big" amount of work (like modifiying CAD files), it might take some time before I actually tackle this.

This I don't know. It might be just a matter of changing the orientation of `finger_1` (all three angles of rotation). Position of the finger seems to be fine, but I cannot be sure.

Since manually finding the correct orientation is pretty much impossible, looking at the CAD model to figure out what is the relative transformation from `link_7` frame (hand) to the frame of `finger_1` link could be the start. One of the images above shows where these frames are positioned with respect to the mesh and how they are rotated. Assuming the CAD is correct, then extracting the orientation from this transformation and applying it for `finger_1` origin is all that's needed.

**Comment by felixmaisonneuve** [comment]
Hi @AndrejOrsula,

Doing some Trial and error, I came up with this combination : 
finger 1 : `finger_origin_rpy="-1.570796327 .649262481663582 1.855"`
finger 2 : `finger_origin_rpy="-1.570796327 .649262481663582 -1.2"`

and it resulted in this :
![image](https://user-images.githubusercontent.com/83971099/144423557-1f6017f0-e3a9-4863-a47d-96bef7047f3f.png)

I don't know where the previous values come from. Simply changing the orientation seems to work just fine. 

Try this combination and see if it reflects your real arm gripper.

Best,
Felix

**Comment by AndrejOrsula** [comment]
Hello @felixmaisonneuve,

Thank you for your time! :smile: Your configuration is definitely an improvement over the current version, and it provides better resemblance to the real gripper. With the angles you provided, the fingers can now be used to form a pinching grasp.

However, due to the manual trial-and-error approach, the contact surfaces of the finger tips are not exactly parallel as they would be on the real gripper. It is not currently my use-case, but I think that the tilted contact surfaces could cause some issues when trying to simulate manipulation of small objects (object could eventually slip out of the gripper when using physics engines that implement rigid-body dynamics). 

Therefore, I believe that analysing CAD model (STEP) in an appropriate software is the only way to get that "exact" origin of `finger_1`. I unfortunately do not currently have access to a setup for doing that.

---

I will just provide more information about why I think that origin of `finger_2` and `finger_3` are correct and should not be modified, whereas `finger_1` requires more than one RPY angle (not just yaw) to be corrected.

When looking at `finger_1`, it is visible that the finger mesh does not properly align with its joint on the base of the hand. Below is an image demonstrating that. This image provides a view from behind the finger when the gripper is closed, using your configuration. Image on the right highlights the lines of what I mean (the finger is tilted with respect to the joint that it's connected to).

<p align="center" float="middle">
  <img width="40.0%" src="https://user-images.githubusercontent.com/22929099/144427613-c978dfbc-9dcc-49ac-9d22-efc8b7c56a86.png" alt="finger 1"/>
  <img width="40.0%" src="https://user-images.githubusercontent.com/22929099/144427637-ef2c3dbd-b47b-4e6b-a6c5-2474983375b1.png" alt="finger 1 (marked)"/>
</p>

It is also visible on the inner side when the hand is open (image from https://github.com/Kinovarobotics/kinova-ros/issues/217 using the original configuration).

<p align="center" float="middle">
  <img width="40.0%" src="https://user-images.githubusercontent.com/22929099/144432888-da263128-602b-49a6-9961-4a314815378d.png" alt="finger 1 from original issue"/>
</p>


However, when looking at `finger_3`, it seems to me that the finger is seated properly (again - illustrated with lines below). Same applies to `finger_2` using the original configuration.

<p align="center" float="middle">
  <img width="40.0%" src="https://user-images.githubusercontent.com/22929099/144427632-0420e96a-5a81-42d7-829b-363cbdc3fee9.png" alt="finger 3"/>
  <img width="40.0%" src="https://user-images.githubusercontent.com/22929099/144427627-6f339637-c24c-4c08-b5a9-2fd9ac1709f6.png" alt="finger 3 (marked)"/>
</p>

**Comment by felixmaisonneuve** [comment]
Hi @AndrejOrsula,

Like you said, I think an analysis of the CAD model is required here if we want to have the "perfect" orientation/position. 
Unfortunately, I cannot start looking into it right now. I will leave this issue open and mark it as "enhancement" and notify it here when future work will be done on this topic. 

What is your current use case? Do you need some specific work to be done related to this issue?
We might be able to find some quick and temporary solution to get you going in the meantime. 

Best,
Felix

**Comment by AndrejOrsula** [comment]
I just found this one - [abr/abr_control/**/jaco2.xml#L130](https://github.com/abr/abr_control/blob/58aa61f40a083db705b8b6d51b53da50ae0edac5/abr_control/arms/jaco2/jaco2.xml#L130). Unfortunately, it uses completely different coordinates, so it's not a straightforward conversion. The script below does the trick.

```python
#!/usr/bin/env python3
import numpy as np
from scipy.spatial.transform import Rotation

rot1 = Rotation.from_quat([0.262085, 0.02762996, -0.10213274, 0.95922726])
rot2 = Rotation.from_euler("xyz", [0.0, -0.5 * np.pi, 0.0])

manual_initial_joint_position_adjustment = 0.0
rot1 = rot1.as_euler("xyz")
rot1 = Rotation.from_euler(
    "xyz", [rot1[0] + manual_initial_joint_position_adjustment, rot1[1], rot1[2]]
)

rpy = (rot1 * rot2).as_euler("xyz")
rpy_xacro_coordinates = (rpy[0] - np.pi, -rpy[1], -rpy[2])
```

The `pitch` (joint position offset) is still a bit wrong because they use a slightly different initial position. I adjusted it manually such that `finger_1` and `finger_2` meet when they have the same joint position (`~1.35`).

**`-1.7047873384941834 0.6476144647144773 1.67317415161155`** seems to be around the desired value. Of course it might be a bit off due to manual adjustment of initial joint position and floating-point precision in the descriptor that I found.
![Screenshot_20211202_183834](https://user-images.githubusercontent.com/22929099/144476901-d73c6d78-ef10-446a-a868-946976011ad0.png)

With this change, it seems to be seated properly. (Sorry for very dark image)
![Screenshot_20211202_184028](https://user-images.githubusercontent.com/22929099/144476905-6fa15ddd-f2ad-47e1-9d66-c1d6b0dff7ee.png)

---

The only thing is that finger tips point slightly in the opposite directions (difficult to show - so you need to see for yourself). I am not sure, but I think it is just that the finger tip is not rounded in the used mesh.

![Screenshot_20211202_185819](https://user-images.githubusercontent.com/22929099/144477419-b3de33a5-afa5-4e86-a2d9-fcd0d2a7ca4f.png)

---

I opened PRs for it below. Please double-check that it doesn't cause any issues on `melodic`/`noetic` (although I don't see any reason why it would).

**Comment by felixmaisonneuve** [comment]
Thank you @AndrejOrsula for this solid work. We really appreciate it. 
I tested it and it looks pretty good. 

About the finger tips, I am not sure what you reffer to. 
If you are talking about this line, I think this is simply an optical illusion
![image](https://user-images.githubusercontent.com/83971099/144601398-0e568130-b924-4e6c-b5fb-930e4c42b7c8.png)

Gripper fingertips aren't square (left), they are more with this "kind of" octogonal shape (right). 
![image](https://user-images.githubusercontent.com/83971099/144601778-31567103-4039-49c1-8de9-0d976dc9a128.png)

I think it creates an illusion from certain angles that gives the impression the fingertip is pointing in the opposite direction. 
Please correct me if I am not looking at the right thing. 

Other than that, thank you again for your support. I already merge both of your pull requests.

Regards,
Felix

**Comment by AndrejOrsula** [comment]
Yes @felixmaisonneuve. That was what I meant, and I think your explanation is correct. Thank you.
