### ISSUE TITLE
How to connect kinova arm at NVIDIA JETSON AGX XAVIER(some variant of the ARM instruction set) platform?

### ISSUE THREAD

**Issue by chenjjjinliang** [Kinovarobotics/kinova-ros#377]
## Summary

A short description of the requested feature.

## Use case

Why is this feature needed?

What are the use case covered by this feature?

## Alternative

Do you have an idea how on how best to implement this enhancement?

If this feature is not implemented, do you have a workaround?

## Possible issues

Anything that could be affected by the new feature.

## Additional context

Any other information you would like us to know about the requested enhancement.

**Comment by felixmaisonneuve** [comment]
Hi @chenjjjinliang,

Some compiled versions of the API for the ARM achitecture were made in the past. You can find the compiled libraries for a raspberry pi 3 [here](https://github.com/Kinovarobotics/kinova_sdk_recompiled/tree/master/raspberry%20pi%203/_SO) and a compiled librairies for the NVIDIA Jetson Tx2 [here](https://github.com/Kinovarobotics/Extra_code_examples_Jaco2arm/tree/master/sdk%20compiled%20for%20tx2). You will need to replace the .so files on your machine by these ones. You can try both and see if you are able to use the arm. 

However, this is not something that we officially support and there is no garanty that any of them will work. 
This is not something that we provide so there is no other options it doesn't work. 

I will close this issue, but feel free to leave a comment if you are able to make it work or not for anyone in the future that would want to do the same thing. 

Regards,
Felix
