### ISSUE TITLE
Error by launching benchmarking

### ISSUE THREAD

**Issue by s265452** [Kinovarobotics/kinova-ros#379]
Hi everyone,

I'm using:

ROS Melodic 18.04
Kinova arm Jaco2 j2s7s300

I wish to launch a banchmarking so I launch:

roslaunch j2s7s300_moveit_config run_benchmark_ompl.launch

and I read:

```
xacro.py is deprecated; please use xacro instead
xacro: in-order processing became default in ROS Melodic. You can drop the option.
xacro: in-order processing became default in ROS Melodic. You can drop the option.

RLException: [/home/francesco/catkin_ws/src/kinova-ros/kinova_moveit/robot_configs/j2s7s300_moveit_config/launch/run_benchmark_ompl.launch] requires the 'cfg' arg to be set
The traceback for the exception was written to the log file
```

Waiting for your answers.

**Comment by felixmaisonneuve** [comment]
Hi,

you will need to change this line : 
https://github.com/Kinovarobotics/kinova-ros/blob/93f66822ec073827eac5de59ebc2a3c5f06bf17f/kinova_moveit/robot_configs/j2s7s300_moveit_config/launch/run_benchmark_ompl.launch#L4

Something similar to this I suppose (I have never done that) : 
https://github.com/ros-planning/moveit/blob/e12053f9a8316225747e0720df9abaf599689c89/moveit_ros/benchmarks/examples/demo_panda_all_planners_obstacles.launch#L3

I don't know if these arguments are required, but I suppose you could also remove the arguments for your benchmark execution : 
https://github.com/Kinovarobotics/kinova-ros/blob/93f66822ec073827eac5de59ebc2a3c5f06bf17f/kinova_moveit/robot_configs/j2s7s300_moveit_config/launch/run_benchmark_ompl.launch#L17
 to (removed `args="$(arg cfg)`)
```
  <node name="$(anon moveit_benchmark)" pkg="moveit_ros_benchmarks" type="moveit_run_benchmark" --benchmark-planners" respawn="false" output="screen">
```

I don't know what this argument file is used for.

Regards,
Felix

**Comment by felixmaisonneuve** [comment]
Hi @s265452 

Do you still need support regarding benchmarking or did you manage to make it work?

I will close this issue in a couple of weeks if I don't get an answer from you by then.

Best,
Felix
