### ISSUE TITLE
position error becomes larger with a custom joint_trajectory_controller

### ISSUE THREAD

**Issue by Lu-fm** [Kinovarobotics/kinova-ros#387]
## Description
Hi there! I am doing some controller design with the  KINOVA gen2 robot arm. First the planned trajectory from move_group was generated and sent to the action server, then I modified the joint_trajectory_controller in kinova_driver pkg to implement my control algorithm.  However, I found that the trajectory tracking error is much larger than that using the origin jonit_trajectory_controller.

## Version

ROS distribution : 
noetic
Branch and commit you are using : 
kinetic-devel v1.2.1

## Steps to reproduce

 I conduct some experiments:

Move the robot with a displacement of 0.200 m in Z direction. (Note that I also created a custom kinova_arm_driver.cpp in my pkg, but it's the same as the original one in the following experiments).

1. Use the original kinova_arm_driver node in kinova_driver pkg, actual displacement: 0.196 m
2. In my custom kinova_arm_driver.cpp, use the joint_trajectory_controller class defined in kinova_driver pkg, actual displacement: 0.193 m
3. In my custom kinova_arm_driver.cpp, use the joint_trajectory_controller class defined in my custom joint_trajectory_controller.cpp. This file is copied from the joint_trajectory_controller.cpp in the kinova_driver,  and I only change the name of the class, actual displacement: 0.184 m

## Code example (if necessary)

```
    # paste code here #
```

## Expected behavior

Describe the expected behavior (in regard to the bug described above).

## Any other information

Any other information you believe the maintainers need to know.

**Comment by felixmaisonneuve** [comment]
Hi @Lu-fm,

The Jaco2 arm is not very precise.  It is normal to see movements to be a couple centimeters off. 

I think there is nothing wrong with your controller and, if you do more testing, the opposite might happen (your controller being more precise). 

Did you try to run multiple tests with each controllers?

Best,
Felix

**Comment by Lu-fm** [comment]
Hi @felixmaisonneuve ,

I have done more tests, and found that the large error may come from the scaling factor in my trajectory planner. (I just let ```cpp velocity *= scale; time /= scale``` , which is not exactly true.) So I turn the scale factor to 1, and the result shows that the performance of the  origin controller and the copied controller are close with an average error of 5mm, which is close to that of the kinova pose client. 
![mmexport1650724381196](https://user-images.githubusercontent.com/56502126/164910590-ad807880-86d1-40f0-9f9d-8b104c54a8d5.jpg)

Thank you for your reply.
 Best,
Fangmin

**Comment by felixmaisonneuve** [comment]
Great!
I will close this issue since you found the source of your displacement gab. 
If you have any other problem or question, feel free to reopen this issue or open a new one.

Best,
Felix
