### ISSUE TITLE
Xavier Support for Gen2 ARM

### ISSUE THREAD

**Issue by sreesms** [Kinovarobotics/kinova-ros#403]
I would like to connect Kinova Gen2 with Xavier. When I tried to launch file USB connection issue comes.
**USBCommandLayerUbuntu.so: cannot open shared object file: No such file or directory**

I have tried copying the .so files from https://github.com/Kinovarobotics/Extra_code_examples_Jaco2arm/tree/master/sdk%20compiled%20for%20tx2 to kinova_driver/lib/i386-linux-gnu folder. But it seems not working. Can you please guide on this?

**Comment by felixmaisonneuve** [comment]
Hi @sreesms 

We do not provide official support for other architectures.
I can link you to another of my comment : https://github.com/Kinovarobotics/kinova-ros/issues/290#issuecomment-1260953353

We also provide these files : https://github.com/Kinovarobotics/kinova_sdk_recompiled/tree/master/raspberry%20pi%203

However, if it doesn't work and you still have the same error message, I am affraid there is nothing else I can do for you

Regards,
Felix
