### ISSUE TITLE
Control Jaco2 to move along predefined trajectory with API

### ISSUE THREAD

**Issue by GS-DUT** [Kinovarobotics/kinova-ros#412]
Hi there. I am trying to control Jaco2 to move along predefined trajectory. To do this,  `sendAdvanceTrajectory()` is called to send trajectory points in a fixed frequency. And, the "POSITION_TYPE" of trajectory points are set "ANGULAR_POSITION". However, Jaco2 seems like to decelerate to 0 at each trajectory point, which makes it jitter during movement. Is there any way to make movement smooth without setting "POSITION_TYPE" of trajectory points to "ANGULAR_VELOCITY"?
Looking for reply. Thanks in advance.

**Comment by felixmaisonneuve** [comment]
Hi @GS-DUT,

Unfortunately no, the arm will always decelerate to 0 at each trajectory point. You could move the arm in velocity control, but this is probably not what you are looking for. 

Best,
Felix
