### ISSUE TITLE
Support for expansion board?

### ISSUE THREAD

**Issue by prajapatisarvesh** [Kinovarobotics/kinova-ros#431]
## Summary

Has anyone been successful getting/setting the pinout values for the expansion board? I was adding a custom gripper with j2n6s300 and I couldn't find anything in the API/documentation for the same.

**Comment by smoya23** [comment]
Hi @prajapatisarvesh ,

You can find what you're looking for at pages 16-17 of our user guide. It can be found by going to our [website](https://www.kinovarobotics.com/), clicking on 'Gen 2 Robots' under the 'Products' drop down menu and scrolling down all the way to the 'GEN2 Documentation' section. 

Best, Santiago

**Comment by prajapatisarvesh** [comment]
Thanks for your help!
