### ISSUE TITLE
[Question] Mico arm maximum rate [hz]?

### ISSUE THREAD

**Issue by ffcatarino** [Kinovarobotics/kinova-ros#59]
Hi,

I would like to remotely control the mico arm with a master device (like a joystick). What is the maximum refresh rate of the Mico arm?

And how can I change it?

Thanks.

**Comment by LongfeiProjects** [comment]
The robot status is refreshed at a rate of 100Hz. In other words, the code (reading, setting values etc.) will run every 0.01s. However, I am afraid you are not allowed to change them by yourself.
--
Longfei
