### ISSUE TITLE
Tested/supported ROS/Ubuntu versions

### ISSUE THREAD

**Issue by peci1** [Kinovarobotics/kinova-ros#72]
On which ROS/Ubuntu distributions has the new library been tested? Could you add this information to the main readme?

**Comment by LongfeiProjects** [comment]
Hello, for the kinova-ros development. My ROS version is indigo 1.11.20, and Ubuntu version is 14.04.4.
However, we do realize that people are running kinova-ros with different ROS/Ubuntu versions successfully as well.

I believe my colleague Sid already saw your message, and he will manage the next release.
