### ISSUE TITLE
Issues with joints_action_client code - decrease velocity, joystick switches to joint space control?

### ISSUE THREAD

**Issue by fredrikbaberg** [Kinovarobotics/kinova-ros#74]
I use part of the joints_action_client to move the arm to certain configurations, but have some troubles:
- For what I am testing the joint velocity is a bit too high for having time to manually counter potential collisions, is it possible to set a lower velocity?
- After setting a joint configuration the joystick controls the arm in joint-space instead of cartesian space. Is this a known problem? Is there a fix?
- Is there some way to take (known) obstacles into account when moving to pre-defined joint configurations?

**Comment by soli7** [comment]
1) Currently the joint action server does not allow setting joint velocities. But it makes sense to do that, we will include that in the next release. Till then you can use the velocity control to control joint velocity or use the lower level arm API to give joint commands. 
2) This is how it was intended. To switch back to cartesian, you can give the current pose of the robot as a cartesian command and the robot should be back in cartesian control.
3) You can use MoveIt package for that. We have plans to have a working demo for MoveIt as a part of future releases.
