### ISSUE TITLE
j2n6a300_state_publisher publishing to the wrong namespace?

### ISSUE THREAD

**Issue by fredrikbaberg** [Kinovarobotics/kinova-ros#75]
I've embedded "kinova_bringup/launch/kinova_robot.launch" in a namespace (e.g. "kinova_ns"), which leads to that almost all topics has the correct prefix. The exception is the topic "/j2n6a300_driver/out/joint_state" (subscribed to by "j2n6a300_state_publisher").

I don't think this causes troubles, but it does not look as nice.

**Comment by fredrikbaberg** [comment]
Turns out the problem is slightly larger than I thought: By including the launchfile in a namespace (<group ns="kinova_ns">) the TF tree breaks. That means it seems I can't use namespace with arm-related code for now.

**Comment by fredrikbaberg** [comment]
It would have been nice if this had been solved, the same issue is still present.

**Comment by martine1406** [comment]
Hi @fredrikbaberg 

In the current version of the ros package, there is no more j2n6a300... you should use j2n6s300 prefix if you are working on a jaco2 arm. This is why we did not fix the issue since we do not allow using j2n6a300 anymore. Do you get the same namespace problem for j2n6s300?

**Comment by fredrikbaberg** [comment]
Hi @martine1406, the same issue is there with j2n6s300. See pull request #76.
