### ISSUE TITLE
Parameterize root link

### ISSUE THREAD

**Issue by andre-nguyen** [Kinovarobotics/kinova-ros#79]
I noticed [here](https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_driver/src/kinova_arm_kinematics.cpp#L201) 

``` c++
broadcaster_.sendTransform(tf::StampedTransform(transform, ros::Time::now(),
                                            "root",
                                            concatTfName(tf_prefix_, "link_base")));
```

That the base tf is hard coded to "root". It would be useful to be able to define that as a parameter. In my case, the reason is that the arm is mounted onto other stuff therefore the base link of the arm isn't "root".

**Comment by soli7** [comment]
Thanks for reporting the issue. As you suggested I will parameterize this.
