### ISSUE TITLE
How to record and play the Jaco arm?

### ISSUE THREAD

**Issue by somebodyus** [Kinovarobotics/kinova-ros#80]
I want to record the movement of Jaco arm and play it back.
How to do it?

**Comment by cangjiaxaun** [comment]
Please take a look at 
http://wiki.ros.org/rosbag
it may help

**Comment by somebodyus** [comment]
Which topic should I record?

**Comment by soli7** [comment]
Hi, 

It is upto you what you would like to record. If you just want to play back joint movement, logging just the joint positions should suffice. Topics -
/j2n6a300_driver/out/finger_position
/j2n6a300_driver/out/joint_angles

**Comment by somebodyus** [comment]
Thank you so much.

How can I play it back? Should I feed the positions to some topic? Should I launch the kinova?
