### ISSUE TITLE
The robot model in rviz cannot display the finger movements.

### ISSUE THREAD

**Issue by somebodyus** [Kinovarobotics/kinova-ros#81]
The robot model in rviz cannot display the finger movements. How to solve the problem?

I can control the finger via the python script.

**Comment by soli7** [comment]
Hi,

This issue was reported here - https://github.com/Kinovarobotics/kinova-ros/issues/77
A fix has been suggested there. This fix will be part of the next release.
You can use the fix or wait for the next release.

Thanks,
Sid
