### ISSUE TITLE
questions about MICO2 6DOF

### ISSUE THREAD

**Issue by snowlylover** [Kinovarobotics/kinova-ros#82]
I'm going to buy a manipulator and design my own controller. Can I get the information of motors or the dynamic model of the robot? It's not enough to know the value of voltage or torque. Is MICO robot suitable for me? Thank you~

**Comment by soli7** [comment]
Hi, 
you should get a better response asking this question in kinova.ca support section.

Kinova can provide you with information about the masses, COMs etc, that will be available. Then depending upon what kind of controller you want, we can give you additional information upon request.

~Sid
