### ISSUE TITLE
About Decrease the MaxTranslationVelocity and MaxOrientationVelocity in the Cartesian Space

### ISSUE THREAD

**Issue by Calmjoy** [Kinovarobotics/kinova-ros#84]
I want to decrease the motion velocity of jaco2 in the Cartesian space and tried to add the following code in the kinova_comm.cpp:

> std::cout  << "Max Translation Velocity : " << configuration.MaxTranslationVelocity << std::endl;
std::cout << "Max Orientation Velocity : " << configuration.MaxOrientationVelocity << std::endl;
configuration.MaxTranslationVelocity = 0.04f;
configuration.MaxOrientationVelocity = 0.16f;
setConfig(configuration);
getConfig(configuration);
std::cout << "Modified Max Translation Velocity : " << configuration.MaxTranslationVelocity << std::endl;
std::cout << "Mofified Max Orientation Velocity : " << configuration.MaxOrientationVelocity << std::endl;

This works well for some value of the MaxTranslationVelocity and MaxOrientationVelocity but not for some other values such as 0.01f for MaxTranslationVelocity and 0.05f for MaxOrientationVelocity. 
Could you please tell me is there any restriction on the setting of the value of MaxTranslationVelocity and MaxOrientationVelocity? Thank you so much.

**Comment by martine1406** [comment]
Hi. Sorry for the delay in answering you. We had some restructuring internally. Yes there are restrictions on these values. MaxTranslationVelocity can go from 0.04 to 0.2 (4 cm/sec to 20 cm/sec). Max orientation velocity can go from 0.16 to 1.07 (0.16 rad/sec to 1.07 rad/sec). I hope that helps
