### ISSUE TITLE
Empty model spawns in Gazebo

### ISSUE THREAD

**Issue by deysumitkr** [Kinovarobotics/kinova-ros#86]
On spawning any of the models from  `kinova_description/urdf/*_standalone.xacro` in gazebo, the robot name gets listed in the models spawned but it doesn't have any links. Also the robot is not visible in the world.

[Details with code and images](http://answers.ros.org/question/253267/empty-model-spawned-in-gazebo-kinova-micojaco-xacro/)

**Comment by soli7** [comment]
Gazebo is on the TODO list. You should have the supported models by Feb end.
