### ISSUE TITLE
Gazebo and Rviz simultaneously 

### ISSUE THREAD

**Issue by pietroastolfi** [Kinovarobotics/kinova-ros#90]
Is it already implemented a configuration which allows to communicate Rviz and Gazebo in order to obtain the same movement on gazebo while planning on Rviz?

**Comment by martine1406** [comment]
yes. sorry about the delay in answering your question. you can launch 
roslauch kinova_gazebo robot_launch.launch  kinova_robotType:=(your robot)     (e.g. j2n6s300)
and then
roslaunch (your robot)_moveit_config (your robot)_gazebo_demo.launch

**Comment by Tejas-Shastha** [comment]
This suggestion was useful in that I was able to have control over the gazebo sim using rviz. However, the interactive markers do not appear in rviz for controlling the gripper pose. Any suggestions? 
These markers do appear when I launch roslaunch j2n6s300_moveit_config j2n6s300_virtual_robot_demo.launch.

**Comment by martine1406** [comment]
The interactive markers appear on my end when I launch:
`roslaunch j2n6s300_moveit_config j2n6s300_gazebo_demo.launch`
then
`roslaunch j2n6s300_moveit_config j2n6s300_virtual_robot_demo.launch`
