### ISSUE TITLE
Arm incorrectly restarted

### ISSUE THREAD

**Issue by rongoldman-tri** [Kinovarobotics/kinova-ros#92]
I wrote a GUI E-Stop button that when pressed calls /j2n6s200_driver/in/stop to disable the current (& future) ROS motion commands. However there are bugs in the action servers (kinova_joint_angles_action.cpp, kinova_tool_pose_action.cpp & kinova_fingers_action.cpp) that do not handle the stop properly and result in arm motions being enabled.

I discovered the problem doing a Cartesian motion so will describe the bugs in kinova_tool_pose_action.cpp. Below is the log from the KinovaPoseActionServer immediately after the arm is stopped:

[DEBUG] [1494443408.457872859]: void kinova::KinovaPoseActionServer::actionCallback(const ArmPoseGoalConstPtr&): current_pose X -0.0745834; Y 0.454859; Z 0.16325; ThetaX -3.06009; ThetaY -1.06086; ThetaZ 1.61518
[DEBUG] [1494443408.467820383]: Arm stop requested
[DEBUG] [1494443408.487889440]: The action server has received a new cancel request
[DEBUG] [1494443408.487957696]: Transisitoning to a cancel requested state on goal id: /grab_can-9-1494443326.139, stamp: 1494443326.14
[DEBUG] [1494443408.487999247]: Transisitoning to a cancel requested state on goal id: /grab_can-5-1494443407.785, stamp: 1494443407.78
[DEBUG] [1494443408.488070319]: A preempt has been received by the SimpleActionServer
[DEBUG] [1494443408.488104890]: Setting preempt_request bit for the current goal to TRUE and invoking callback
[ WARN] [1494443408.558068468]: In class [N6kinova10KinovaCommE], function [setCartesianPosition]: The pose could not be set because the arm is stopped

[DEBUG] [1494443408.558118691]: void kinova::KinovaPoseActionServer::actionCallback(const ArmPoseGoalConstPtr&): action server isPreemptRequested
[DEBUG] [1494443408.615829255]: Setting the current goal as canceled
[DEBUG] [1494443408.615886288]: Setting status to canceled on goal, id: /grab_can-5-1494443407.785, stamp: 1494443407.78
[DEBUG] [1494443408.615924293]: Publishing result for goal with id: /grab_can-5-1494443407.785 and stamp: 1494443407.78
[ WARN] [1494443408.616067551]: void kinova::KinovaPoseActionServer::actionCallback(const ArmPoseGoalConstPtr&): LINE 150, setPreempted 
[DEBUG] [1494443408.641966750]: The action server has received a new goal request
[DEBUG] [1494443408.642029680]: A new goal has been recieved by the single goal action server
[DEBUG] [1494443408.642155917]: Accepting a new goal
[DEBUG] [1494443408.642218817]: Accepting goal, id: /grab_can-6-1494443408.618, stamp: 1494443408.62
[DEBUG] [1494443408.643860481]: 

***-----------------------***
void kinova::KinovaPoseActionServer::actionCallback(const ArmPoseGoalConstPtr&):  target X -0.405641; Y 0.471997; Z 0.0443867; ThetaX 3.03278; ThetaY -1.53346; ThetaZ 1.41097
***-----------------------***

What you can see is that it treats the stop as a preemption and when it receives the next motion request it executes it. It should abort it, for example:

[DEBUG] [1494451599.712410948]: The action server has received a new goal request
[DEBUG] [1494451599.712470503]: A new goal has been recieved by the single goal action server
[DEBUG] [1494451599.712551734]: Accepting a new goal
[DEBUG] [1494451599.712611621]: Accepting goal, id: /grab_can-8-1494451599.712, stamp: 1494451599.71
[ INFO] [1494451599.714039105]: Could not complete cartesian action because the arm is 'stopped'.
[DEBUG] [1494451599.714091699]: Setting the current goal as aborted
[DEBUG] [1494451599.714125140]: Setting status to aborted on goal, id: /grab_can-8-1494451599.712, stamp: 1494451599.71
[DEBUG] [1494451599.714168651]: Publishing result for goal with id: /grab_can-8-1494451599.712 and stamp: 1494451599.71
[ WARN] [1494451599.714272152]: void kinova::KinovaPoseActionServer::actionCallback(const ArmPoseGoalConstPtr&): LINE 127, setAborted 

Looking at the code in kinova_tool_pose_action.cpp the bug is that in the inner while loop the test for preempt is done before the test for stop, and for a preempt the arm is stopped & started:

            if (action_server_.isPreemptRequested() || !ros::ok())
            {
                ROS_DEBUG_STREAM("" << __PRETTY_FUNCTION__ << ": action server isPreemptRequested");
                result.pose = feedback.pose;
                arm_comm_.stopAPI();
                arm_comm_.startAPI();
                action_server_.setPreempted(result);
                ROS_WARN_STREAM(__PRETTY_FUNCTION__ << ": LINE " << __LINE__ << ", setPreempted ");
                return;
            }
            else if (arm_comm_.isStopped())
            {
                ROS_DEBUG_STREAM("" << __PRETTY_FUNCTION__ << ": arm_comm_.isStopped()");
                result.pose = feedback.pose;
                action_server_.setAborted(result);
                ROS_WARN_STREAM(__PRETTY_FUNCTION__ << ": LINE " << __LINE__ << ", setAborted ");
                return;
            }

Reversing the two tests makes things work properly:

            if (arm_comm_.isStopped())
            {
                ROS_DEBUG_STREAM("" << __PRETTY_FUNCTION__ << ": arm_comm_.isStopped()");
                result.pose = feedback.pose;
                action_server_.setAborted(result);
                ROS_WARN_STREAM(__PRETTY_FUNCTION__ << ": LINE " << __LINE__ << ", setAborted ");
                return;
            }
            else if (action_server_.isPreemptRequested() || !ros::ok())
            {
                ROS_DEBUG_STREAM("" << __PRETTY_FUNCTION__ << ": action server isPreemptRequested");
                result.pose = feedback.pose;
                arm_comm_.stopAPI();
                arm_comm_.startAPI();
                action_server_.setPreempted(result);
                ROS_WARN_STREAM(__PRETTY_FUNCTION__ << ": LINE " << __LINE__ << ", setPreempted ");
                return;
            }

A second bug occurs in the stall detection code:

            else if ((current_time - last_nonstall_time_).toSec() > stall_interval_seconds_)
            {
                ROS_DEBUG_STREAM("" << __PRETTY_FUNCTION__ << ": stall_interval_seconds_");
                // Check if the full stall condition has been meet
                result.pose = feedback.pose;
                arm_comm_.stopAPI();
                arm_comm_.startAPI();
                //why preempted, if the robot is stalled, trajectory/action failed!
                /*
                action_server_.setPreempted(result);
                ROS_WARN_STREAM(__PRETTY_FUNCTION__ << ": LINE " << __LINE__ << ", setPreempted ");
                */
                action_server_.setAborted(result);
                ROS_WARN_STREAM(__PRETTY_FUNCTION__ << ": LINE " << __LINE__ << ", Trajectory command failed ");
                return;
            }

that can also restart the arm if it was stopped. Wrapping the stop/start calls fixes this:

                if (!arm_comm_.isStopped())
                {
                  arm_comm_.stopAPI();
                  arm_comm_.startAPI();
                }

Similar bugs exist in kinova_joint_angles_action.cpp & kinova_fingers_action.cpp.

-- Ron --

**Comment by Kinova** [comment]
Thank you Ron. We will fix that for our next release.
