### ISSUE TITLE
Include Proper License file for package

### ISSUE THREAD

**Issue by rcory** [Kinovarobotics/kinova-ros#93]
The `package.xml` file in the kinova_description folder has a license entry that states BSD. However, including a proper LICENSE.TXT file would be even better.

**Comment by Kinova** [comment]
Hi rcopy

okay thank you for the suggestion. We'll consider it.

**Comment by alimuldal** [comment]
Please consider reopening this. "BSD" is ambiguous, since there are [multiple different BSD licenses](https://en.wikipedia.org/wiki/BSD_licenses). Are you referring to the 2, 3, or 4-clause version?
